### ISSUE TITLE
~10 sec. sound delay

### ISSUE THREAD

**Issue by beta-tester** [raspberrypi/linux#388]
i hope this is the correct place to report issues, related to Raspbian SD card images.

"2013-02-09-wheezy-raspbian.img" was the last working rapbian image, where stella (3.7.2-1) sound is/was working well.
(Stella is an Atari 2600 emulator).

from "2013-05-25-wheezy-raspbian.img" up to the most recent "2013-09-25-wheezy-raspbian.img", when using stella, the sound is delayed round about ~10 seconds.

you can find the full thread of this issue here: http://www.raspberrypi.org/phpBB3/viewtopic.php?f=78&t=52387&hilit=Stella

**Comment by popcornmix** [comment]
It's hard to imagine a 10 second audio delay coming from alsa driver, but it should be possible to confirm this.
The thread suggests the problem didn't occur with 2013-05-25-wheezy-raspbian but does with newer versions.

Can you try reverting your firmware to an older version.

If you look here:
https://github.com/Hexxeh/rpi-firmware/commits/master

you see a list of commits. You can revert to an older commit with:
`sudo rpi-update <git-hash>`

e.g. you could revert to 24th May (which should match the older raspbian image) with:
`sudo rpi-update 001a8517f67182c278e1eff33f1fc2aac0bb22cc`

**Comment by beta-tester** [comment]
2013-05-25-wheezy-raspbian.img is already the first image that shows up that issue...

how i installed Raspbian / Stella til now:
1. installed virgin most recent Raspbian SD image to a blank SD card.
2. setup/update raspbian to most recent state
2.1. sudo apt-get raspi-config
2.2. (optional) sudo apt-get dist-upgrade
2.3. (optional) sudo rip-update
2.4. (optional) sudo reboot
3. sudo apt-get update
4. sudo apt-get install stella

thank you, i will try to "downgrade" rpi-firmware to (Feb 07, 2013 )
sudo rpi-update 1b2fee4c748b4a05f0492dcc708d81f739e6b8ca

**Comment by popcornmix** [comment]
Sure, if you can find any older version that works better, then we can try to identify the commit that caused the problem. The alsa driver hasn't changed since:
https://github.com/raspberrypi/linux/commit/bad49c21520ddc40d512a0d424cbc94f20068e6c
so that is a possibility.

**Comment by beta-tester** [comment]
i didn't know that "downgrade" possibility.
i try out to find the transition between working and non-working commit, and let you know - will take a while...

**Comment by beta-tester** [comment]
ok, i figured out the last working and the first non-working commit:

Mar 18, 2013: https://github.com/Hexxeh/rpi-firmware/commit/aea9d8e529baf2c11e0282706b71ae8cfc8ee909 - good
Mar 24, 2013: https://github.com/Hexxeh/rpi-firmware/commit/61f7aa5742bc8f07be2378d727ac8dc14268e848 - (bricks sd image)
Mar 29, 2013: https://github.com/Hexxeh/rpi-firmware/commit/b68696fa24c2512e91903b8e202502e7c21f325b - bad

i tested with different images as base and applied the upgrade/downgrade:
2013-02-09-wheezy-raspbian.img - upgraded
2013-09-25-wheezy-raspbian.img - downgraded

on commit "Mar 24, 2013: https://github.com/Hexxeh/rpi-firmware/commit/61f7aa5742bc8f07be2378d727ac8dc14268e848" there is a comment about "Firmware: new alsa scheme should fix hangs with libretro" - maybe that is the cause of this issue.

PS.: using "sudo rpi-update ..." in raspbian on a NOOBS 1.3 sd card with OpenELEC and Raspbian may brick your installation!

PPS.:  :oops: is it possible, that i just lost my warranty for my new RPi? because my config.txt contained legal "medium" overclocking options before i downgraded, but i think older rpi-firmware will detect these newer legal overclocking parameters as illegal ones and setted the "voided warranty" flag. :/

**Comment by popcornmix** [comment]
Thanks for digging.
Looks like a firmware issue (start.elf) rather than a kernel one. Occurred on March 24:
"Add additional queue that alsa buffers get stored in before being submitted to audioplus.
Avoid the pwm post process operation by converting in mixing buffer."

Unfortunately that was quite a big change - I'll need to do some debugging.
If you explain exactly how to reproduce the issue that would help.

**Comment by beta-tester** [comment]
1. download a rom that plays sound, just when you start the rom or any other where you can see and hear if the sound is delayed or not (for example a free legal homebrew rom:  latest 'stable' release of "flapping.bin" from http://alienbill.com/2600/flapping/)
   wget http://alienbill.com/2600/flapping/flapping.bin
2. put the rom to a place, where you will find it easily (e.g. to your ~/.)
3. install stella with:
   sudo apt-get -y install stella
4. start stella with:
   stella
5. at first initial start, stella ask you for the roms path... hit [OK] and choose that path where you put the rom to (you will not see the rom yet). [QUIT] stella.
6. start stella again and select the rom and hit [ENTER]-key, to start the rom.
7. when everything is ok, you will hear immediately sound with seeing the screen. if not, and you hear the sound with a big delay of many seconds (and the sound also keeps playing for a moment after you hit [ESC]-key to cancel the rom and go to menu), then the sound issue/bug is present.
8. quit stella
9. change the compilation/debugging or what ever you can do to fix the sound delay issue.
   ... redo steps beginning from step 6.

PS.: do not run stella from startx - just start it from the standard login console - but not SSH session ;)
PPS.: when you follow these steps (6. ... 9.), the sound is not delayed ~10sec. it is lesser, but still very noticeable.
specially when the sound still plays after hit [ESC] or at in-game play.
you can start the in-game play by hitting [SPACE] after starting the rom. you will hear a short beep exactly when the ball disappears from the screen.

hopefully you will find an easy solution - thanks in advance...

**Comment by popcornmix** [comment]
Okay, I can run stella and get the delay. Step 1...

**Comment by popcornmix** [comment]
Some notes:
Running "stella flapper.dat" doesn't have the (big) delay
The stella file browser screen is outputting (silent) audio.
The sample rate is 31,400. 2 channel. 8 bits.
In the first second, stella wrote 120KB of data which is roughly double what I'd expect.
So either stella has a bug, or we are confusing it.
Due to more data being written than is being consumed, the audio latency increases until our buffers fill (10 seconds).

I think the problem is that internally we convert the 8 bit data to 16 bit.
We incorrectly tell stella we have consumed the size of the 16 bit data, rather than the 8 bit data.
stella therefore submits more data than we can cope with.

I've committed a fix and rebuild firmware. Can you rpi-update and test?

**Comment by beta-tester** [comment]
hey, you fixed it! and so quick :D
it works like charm again... thank your so much!!!

PS.: i say thank you, in the name of many others form other forums... "Please send kudos to the appropriate folks"... done

**Comment by popcornmix** [comment]
No problems - thanks for providing the information required to fix it.

**Comment by yusufk** [comment]
Hello, as a user, how does one get rid of the problem?

I just ran:
sudo rpi-update
sudo reboot

and the problem is still there.

**Comment by popcornmix** [comment]
What does "vcgencmd version" report?
What are you running to see the delay?

**Comment by yusufk** [comment]
Jan 10 2014 16:58:06 
Copyright (c) 2012 Broadcom
version efa116b5c8859c352322cb27e13baccbea583ef7 (clean) (release)

I am trying to get espeak to work on my Raspberry Pi

**Comment by popcornmix** [comment]
@yusufk 
I think your problem is an instance of https://github.com/raspberrypi/linux/issues/304.
I'll ping @martinezjavier who was going to investigate this.

**Comment by yusufk** [comment]
Ok, thanks for the reply
