### ISSUE TITLE
Please add MCP9808 sensor support to i2c-sensor dtoverlay list

### ISSUE THREAD

**Issue by Jibun-no-Kage** [raspberrypi/linux#5234]
### Describe the bug

Not a bug but a support request.  Please add MCP9808 sensor support to i2c-sensor dtoverlay list.  As I understand it, this sensor already is supported by the Linux kernel?  Thanks.

### Steps to reproduce the behaviour

NA

### Device (s)

Other

### System

Latest Raspberry Pi firmware image (or so I believe what is how support is implemented).

### Additional context

Just a suggestion but maybe setup a sub section on github under the Raspberry Pi area for such requests?

**Comment by pelwell** [comment]
Done - see https://github.com/raspberrypi/linux/commit/ac4cf1b984f0b3473460af866eef536765b60865.

GitHub doesn't allow the creation of arbitrary sections, and requesting additions via the Issues page works for us.

**Comment by Jibun-no-Kage** [comment]
Cool, I just did not want to post the requests the wrong way or such.  I should be able to test MCP9808 sensor first thing tomorrow, once I get the update.

**Comment by Jibun-no-Kage** [comment]
Is this update published yet?  Ran rpi-update on a Pi4, then added dtoverlay=i2c-sensor,mcp980x,addr=0x18 to /boot/config.txt, and rebooted, but did not see the typical UU on i2c-detect -y 1 scan?  Shows 18 as address rather than UU.

**Comment by pelwell** [comment]
Not yet - the last update was on Monday. You can see the release history here: https://github.com/raspberrypi/rpi-firmware/commits/master

**Comment by Jibun-no-Kage** [comment]
Excellent, that is going to be a book mark!  Thanks.

**Comment by popcornmix** [comment]
rpi-update contains this now.

**Comment by Jibun-no-Kage** [comment]
Excellent!  Yup, now see kernel/dtoverlay control of the sensor, i.e. UU in i2c address slot (0x18) in the i2c detect result.

**Comment by Jibun-no-Kage** [comment]
Odd... the direct query of temp1_input under kernel/dtoverlay... the result is '62' which does not make sense.  So I pulled the sample test script from Adafruit, and after loading the dependencies, and running the simple test, the results were as expected.

\# cd /root
\# apt install build-essential python3-dev python3-pip python3-smbus git
\# pip3 install RPi.GPIO
\# git clone https://github.com/adafruit/Adafruit_Python_MCP9808.git
\# cd Adafruit_Python_MCP9808
\# python3 setup.py install

\# cd examples
\# python3 simpletest.py
Temperature: 27.250*C / 81.050*F
Temperature: 27.312*C / 81.162*F
Temperature: 27.312*C / 81.162*F
Temperature: 27.250*C / 81.050*F

The dtoverlay just provides visibility to the native kernel support, right?  Thus, I am not sure this is Raspberry Pi issue to solve, but documented here to illustrate there seems to be an issue with the existing kernel support for MCP9808 sensor.

**Comment by Jibun-no-Kage** [comment]
Ah, thanks! Look forward to testing.

**Comment by pelwell** [comment]
Oh dear. The `mcp980x` driver only supports the `MCP980<x>` family of devices when `x` is in the range 0-3. For MCP9804, MCP9805 and MCP9808 one needs the `jc42` driver (obviously). Looking back at my commit I think the only thing wrong was the README comment, and the fact that it didn't solve your problem.

I'll add a `jc42` option to the i2c-sensor overlay.

**Comment by pelwell** [comment]
https://github.com/raspberrypi/linux/commit/41d7f478e800a31dc8d1e85d199bc9e660b12074 is the update to the overlay. To save you waiting for the next build you can download a patched overlay here: https://drive.google.com/file/d/1eWeA3oRhVTrYI1Y57HLoXzy_dhXmQOd8/view?usp=share_link

Just `sudo cp i2c-sensor.dtbo /boot/overlays/`, edit config.txt to say `dtoverlay=i2c-sensor,jc42` and reboot.

**Comment by Jibun-no-Kage** [comment]
Wow, I pulled the C source for the support of the MCP9808, but have not had time to review it as yet.  Interesting.

First test is odd, after reboot...

\# cat /sys/devices/platform/soc/fe804000.i2c/i2c-1/1-0018/hwmon/hwmon2/temp1_input
0
\# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         08 09 0a 0b 0c 0d 0e 0f
10: 10 11 12 13 14 15 16 17 UU 19 1a 1b 1c 1d 1e 1f
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f
30: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f
60: 60 61 62 63 64 65 66 67 UU 69 6a 6b 6c 6d 6e 6f
70: 70 71 72 73 74 75 76 77

Look like the changes are flooding blasting the i2c bus?

I set boot/config.txt to...

dtoverlay=i2c-sensor,jc42
dtoverlay=i2c-sensor,mcp980x,addr=0x18

I pulled the VCC from the sensor, to reset it, and then got...

\# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

Not sure where 0x68 is coming from, I only have 1 device on the i2c bus.

But still can seem to read the sensor right...

\# cat /sys/devices/platform/soc/fe804000.i2c/i2c-1/1-0018/hwmon/hwmon2/temp1_input
62

Of course if I use the python script...

\# python3 simpletest.py
Press Ctrl-C to quit.
Temperature: 28.000*C / 82.400*F
Temperature: 27.938*C / 82.287*F
Temperature: 28.000*C / 82.400*F

**Comment by Jibun-no-Kage** [comment]
Did one more reboot... And the phantom 0x68 is gone, and i2c detect scan clear...

\# i2cdetect -y 1
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
But the sensor read is still not right...

\# cat /sys/devices/platform/soc/fe804000.i2c/i2c-1/1-0018/hwmon/hwmon2/temp1_input
62

**Comment by pelwell** [comment]
You need to remove the usage of `mcp980x` - it's probably getting in the way.

**Comment by Jibun-no-Kage** [comment]
Testing now... just with the 'dtoverlay=i2c-sensor,jc42' or 'dtoverlay=i2c-sensor,jc42,addr=0x18' the typical UU is not present, just the raw address of 0x18.  So, does not appear the kernel has control or access to the sensor.

\# ls -l /sys/devices/platform/soc/fe804000.i2c/i2c-1/1-0018/
total 0
-r--r--r-- 1 root root 4096 Nov  7 17:30 modalias
-r--r--r-- 1 root root 4096 Nov  7 17:27 name
lrwxrwxrwx 1 root root    0 Nov  7 17:30 of_node -> ../../../../../../firmware/devicetree/base/soc/i2c@7e804000/jc42@18
drwxr-xr-x 2 root root    0 Nov  7 17:30 power
lrwxrwxrwx 1 root root    0 Nov  7 17:30 subsystem -> ../../../../../../bus/i2c
-rw-r--r-- 1 root root 4096 Nov  7 17:26 uevent
-r--r--r-- 1 root root 4096 Nov  7 17:30 waiting_for_supplier

There is not temp1_input file, so can't query for temperature via CLI. But, clearly the jc42 driver loaded...

\# cat /sys/devices/platform/soc/fe804000.i2c/i2c-1/1-0018/name
jc-42.4-temp

What is interesting,is the mcp9808 is show as compatible.

Required properties:
- compatible: May include a device-specific string consisting of the
	      manufacturer and the name of the chip. A list of supported
	      chip names follows.
	      Must include "jedec,jc-42.4-temp" for any Jedec JC-42.4
	      compatible temperature sensor.

microchip,mcp9808

**Comment by Jibun-no-Kage** [comment]
But looking at the actual kernel patch for JEDEC?  They don't list the MCP9808...
https://linux.kernel.narkive.com/fFuXz9Ak/patch-hwmon-add-support-for-jedec-jc-42-4-compliant-temperature-sensors

+ * Microchip MCP9805, MCP98242, MCP98243, MCP9843
+ Prefixes: 'mcp9805', 'mcp98242', 'mcp98243', 'mcp9843'
+ Addresses scanned: I2C 0x18 - 0x1f

So I wonder if the actual kernel patch is missing what is otherwise documented?  I only see references to the MCP9805.

The cool thing is the since you added the JEDEC compatibles that adds a lot of additional sensors to the pool.  :) But we don't have the one i need working quite yet.

**Comment by Jibun-no-Kage** [comment]
I don't have a Pi setup to execute C source correctly, and I have little experience with C in Linux, versus on Macintosh and PC.  If I can setup a C environment, but that would be the actual proof, to run the raw C code that the kernel has, right?

**Comment by pelwell** [comment]
https://github.com/raspberrypi/linux/blob/rpi-5.15.y/drivers/hwmon/jc42.c#L175

**Comment by Jibun-no-Kage** [comment]
Yup... { MCP_MANID, MCP9808_DEVID, MCP9808_DEVID_MASK },  That is good then,  I am trying to brute force load the driver.

THAT WORKED!
https://www.kernel.org/doc/html/latest/hwmon/jc42.html

\# modprobe jc42
\# echo jc42 0x18 > /sys/bus/i2c/devices/i2c-1/new_device

\# cat /sys/devices/platform/soc/fe804000.i2c/i2c-1/1-0018/hwmon/hwmon2/temp1_input
26562

So is what I did above not basically what the overlay is going to do?

**Comment by Jibun-no-Kage** [comment]
I happen to do the above on 64 bit as well! LOL

**Comment by Jibun-no-Kage** [comment]
Ah, I will test int he next day or so.  Thanks!

**Comment by Jibun-no-Kage** [comment]
Either I have missed something, or this does not seem to be working  Have a Pi Zero, with i2c enabled, and latest rpi-update done.  The i2c module is loaded, but I don't see 'UU' at address 0x18 (for MCP9808.  The jc42 module is loaded as well.

\# lsmod | grep jc42
jc42                   16384  0
\# lsmod | grep i2c
i2c_bcm2835            16384  0
i2c_dev                16384  0

\# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- 18 -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

And /boot/config.txt...
\# cat /boot/config.txt | grep i2c-sensor
dtoverlay=i2c-sensor,jc42

There is not a temp1_input file, and there should be...
\# find / | grep 1-0018
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/subsystem
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/power
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/power/runtime_suspended_time
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/power/autosuspend_delay_ms
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/power/runtime_active_time
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/power/control
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/power/runtime_status
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/waiting_for_supplier
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/modalias
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/uevent
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/name
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/of_node

However if I remove the overlay from the configuration and reboot, then force the driver...
\# lsmod | grep jc42
[No Output]

\# modprobe jc42
\# echo jc42 0x18 > /sys/bus/i2c/devices/i2c-1/new_device

\# /usr/sbin/i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

\# find / | grep 1-0018 | grep input
/sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/hwmon/hwmon2/temp1_input

\# cat /sys/devices/platform/soc/20804000.i2c/i2c-1/1-0018/hwmon/hwmon2/temp1_input
26062

Then I can access the sensor data as expected.  So clearly the overlay is not working right?

**Comment by pelwell** [comment]
Having got my hands on one of these I noticed a warning message in the kernel log:
```
[    9.567522] jc42: probe of 1-0018 failed with error -121
```
Unfortunately, not all devices support the disabling of the SMBUS timeout, and the driver treats attempting to do so on a non-supporting chip as a fatal error. I've pushed an update to the i2c-sensor overlay adding a `no_timeout` parameter - not using the parameter on an MCP9808 makes it work.

**Comment by Jibun-no-Kage** [comment]
Dang, I missed that, I should have caught that.  So this will be live via rpi-update when?  As I recall you only push out changes like once a week?  Odd, that when I load the driver via modprobe, and force a new i2c device to be created... that works.  Wonder if forcing the new device by default sets no_timeout?  Interesting.  Again, thank for doing this, really appreciate it.  It sort of became a bigger effort than expected.

I pickup sensors pretty often for projects I do, so if you never need someone to help test a given sensor, and I have it or expect to use it, be glad to help test in the future.

**Comment by pelwell** [comment]
Updates are pushed as and when we feel they are needed. It's approaching a week since the last update so I would expect one fairly soon, but in the meantime you can download a trial build of the overlay from here: https://drive.google.com/file/d/1eWeA3oRhVTrYI1Y57HLoXzy_dhXmQOd8/view?usp=share_link

**Comment by pelwell** [comment]
Without a device to test, overlay changes like this are strictly best-guess, which in this case wasn't good enough.

Kudos to Pimoroni for the next-day delivery.

**Comment by Jibun-no-Kage** [comment]
Done and done... just got a chance to test this.  Not that I doubted mind you.  Thanks for the test file, worked fine.

**Comment by Nodi-Rubrum** [comment]
Looks some thing has broken this... on Pi OS 13... This happens to be on a pi 5 running 32bit... creating image that will be deployed to Pi Zeros... hence the 32 bit...
```
# dmesg | grep jc42
[    7.605617] i2c i2c-1: of_i2c: Failure registering /axi/pcie@1000120000/rp1/i2c@74000/jc42@18
[    7.605621] i2c i2c-1: Failed to create I2C device for /axi/pcie@1000120000/rp1/i2c@74000/jc42@18
[  147.540310] i2c i2c-1: Failed to register i2c client jc42 at 0x18 (-16)
```
```
# cat /boot/firmware/config.txt | grep i2c-sensor
dtoverlay=i2c-sensor,jc42
dtoverlay=i2c-sensor,mcp980x,addr=0x18
```
I did not test this on 32 bit OS last time...
```
# uname -a
Linux test 6.12.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.62-1+rpt1 (2025-12-18) aarch64 GNU/Linux
```
```
# cat /boot/firmware/config.txt | grep 64
# Do Not Use 64 Bit Mode...
arm_64bit=0
```
```
# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 13 (trixie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="13"
VERSION="13 (trixie)"
VERSION_CODENAME=trixie
DEBIAN_VERSION_FULL=13.2
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by pelwell** [comment]
```
Linux test 6.12.62+rpt-rpi-v8 
```
Your Pi 5 isn't running a 32-bit kernel because it can't - the A76 is 64-bit only except in user mode.

```
[    7.605617] i2c i2c-1: of_i2c: Failure registering /axi/pcie@1000120000/rp1/i2c@74000/jc42@18
[    7.605621] i2c i2c-1: Failed to create I2C device for /axi/pcie@1000120000/rp1/i2c@74000/jc42@18
[  147.540310] i2c i2c-1: Failed to register i2c client jc42 at 0x18 (-16)
# cat /boot/firmware/config.txt | grep i2c-sensor
dtoverlay=i2c-sensor,jc42
dtoverlay=i2c-sensor,mcp980x,addr=0x18
```
The answer's right here - the jc42's default address is 0x18, which is the same as the mcp980x address you are trying to use, and they are clashing. Change one of them - use `i2cdetect -y 1` with the devices attached singly to work out which is which.

**Comment by Nodi-Rubrum** [comment]
I read above that jc42 is required by mcp980x.  So tried to add it, but of course it clashed.  Tried to explicitly load it... via echo command again as exampled above, it also failed.  As a sanity check, loaded the adafruit support, it worked.  So returned back the the overlay only for mcp9808, i.e. 980x, and still getting that odd 62 value.  The last time this happened it was the jc42 load failure, see above.

Adafruit...  Validates the sensor and wiring is correct...
```
# /root/mcp9808/bin/python ./test-mcp9808.py
Temperature: 30.5 C 86.9 F
Temperature: 30.4375 C 86.7875 F
Temperature: 30.4375 C 86.7875 F
Temperature: 30.375 C 86.675 F
```

Back to only using the overlay as noted above...
```
# cat /boot/firmware/config.txt  | grep mcp980x
dtoverlay=i2c-sensor,mcp980x,addr=0x18
```
So mcp9808 loads... but the result from temp1_input is 62 when it should be comparable to above say 30437 or so.
```
# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
```
# find /sys | grep 1-0018 | grep temp1
/sys/devices/platform/axi/1000120000.pcie/1f00074000.i2c/i2c-1/1-0018/hwmon/hwmon6/temp1_input
/sys/devices/platform/axi/1000120000.pcie/1f00074000.i2c/i2c-1/1-0018/hwmon/hwmon6/temp1_max_hyst
/sys/devices/platform/axi/1000120000.pcie/1f00074000.i2c/i2c-1/1-0018/hwmon/hwmon6/temp1_max
```
```
# cat /sys/devices/platform/axi/1000120000.pcie/1f00074000.i2c/i2c-1/1-0018/hwmon/hwmon6/temp1_input
62
```
This is the same behavior as above, 62 until jc42 was explicitly loaded.  Tried...
```
# modprobe jc42
[no output]
# lsmod | grep jc42
jc42                   12288  0
regmap_i2c             12288  2 lm75,jc42
```
OK so overlay pulled jc42 in, but got...
```
# dmesg | grep jc42
[  367.432194] i2c i2c-1: Failed to register i2c client jc42 at 0x18 (-16)
```
So even as the overlay is pulling jc42 in?  Error, right?  So the core issue is still jc42 failing no?  EBUS error -16 if memory serves?  mcp9808 is a jc42 class sensor, so what worked above is not working now.  Only difference between above and now is 64 versus 32 bit OS... that should not be a factor per se IMHO.  What am I missing?

I noticed one really odd thing as well... why is lm75 sensor even referenced?
```
[    8.517168] lm75 1-0018: supply vs not found, using dummy regulator
[    8.524463] hwmon hwmon6: temp1_input not attached to any thermal zone
[    8.524473] lm75 1-0018: hwmon6: sensor 'mcp980x'
```
I don't recall seeing that in the original testing above ever.  I have only 1 sensor, explicitly an mcp9808 connected on the i2c bus.

Check Register 0x06 (Device ID): The MCP9808 should return a specific Manufacturer ID and Device ID, which differs from the LM75.  Could the overlay being misidentifying the sensor?

**Comment by Nodi-Rubrum** [comment]
I also tried... given the documentation reference to leverage the jc42 option...
```
dtoverlay=i2c-sensor,jc42,mcp980x,addr=0x18
```
Did not recall having to do this previously.  Results...
```
dmesg | grep i2c
[    7.184919] i2c_dev: i2c /dev entries driver
[    7.926749] i2c i2c-1: Failed to register i2c client jc-42.4-temp at 0x18 (-16)
[    7.926758] i2c i2c-1: of_i2c: Failure registering /axi/pcie@1000120000/rp1/i2c@74000/jc42@18
[    7.926763] i2c i2c-1: Failed to create I2C device for /axi/pcie@1000120000/rp1/i2c@74000/jc42@18
```

**Comment by pelwell** [comment]
> I read above that jc42 is required by mcp980x

Oh dear, that's not what was meant, and I don't think it's even true. Support for the MCP908X family is provided by the `lm75` driver; the JC42 has its own dedicated driver (`jc42`).

All you should need is:
```
dtoverlay=i2c-sensor,mcp980x
```
(address 0x18 is the default)

**Comment by Nodi-Rubrum** [comment]
Will give it a shot again, clean image, as well.  So what was attempted in this thread above, was in error?  If I understand your reply correctly.

And will test on 32 bit capable hardware, since that was intended... was trying to avoid the long DKMS compiles on a Pi Zero for other aspects of the project, using Pi Zeros as remote environment monitors... using USB wifi for Pi Zeros without native wifi.

**Comment by pelwell** [comment]
From looking more closely at the `jc42` driver, it appears to support the MCP9804 and MCP9808. I'm not in a position to test this, not having either device, but it does sound like you could just use `dtoverlay=i2c-sensor,jc42` (0x18 is the default address) and get some level of functionality.

**Comment by Nodi-Rubrum** [comment]
Yup... will give it a shot... I should have some time tomorrow to attempt a bit more testing.  Thanks for the help.

**Comment by Nodi-Rubrum** [comment]
Confirmed just using jc42...
```
# cat /boot/firmware/config.txt | grep -E "^dtoverlay"
dtoverlay=dwc2,dr_mode=host
dtoverlay=disable-bt
dtoverlay=i2c-sensor,jc42,addr=0x18
```
Works for polling temperature...
```
# cat /sys/devices/platform/axi/1000120000.pcie/1f00074000.i2c/i2c-1/1-0018/hwmon/hwmon6/temp1_input
25187
```
Thanks again.
