### ISSUE TITLE
Ubuntu 24.04 - max98357a overlay not working

### ISSUE THREAD

**Issue by Nate711** [raspberrypi/linux#6160]
### Describe the bug

I'm unable to load the overlay for the max98357a.

```
pi@ubuntu:~$ sudo dtoverlay max98357a
DTOVERLAY[warn]: no matching platform found

pi@ubuntu:~$ aplay -l
aplay: device_list:277: no soundcards found...
```

I'm entirely unfamiliar with how modules and overlays work so not sure how to continue. Thanks!

### Steps to reproduce the behaviour

Install Ubuntu Server 24.04 LTS 64-bit using the Raspberry Pi Imager
Add `dtoverlay=max98357a` to end of `/boot/firmware/config.txt`
Run `sudo dtoverlay max98357a` 
(I know editing the config should be enough but I didn't see any errors in dmesg so I used the dtoverlay cli to manifest an error)

### Device (s)

Raspberry Pi 5

### System

```
pi@ubuntu:~$ vcgencmd version
2023/10/30 16:45:10
Copyright (c) 2012 Broadcom
version 30de0ba5 (release) (embedded)

pi@ubuntu:~$ uname -r
6.8.0-1004-raspi
```

### Logs

> pi@ubuntu:~$ sudo dmesg
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x414fd0b1]
[    0.000000] Linux version 6.8.0-1004-raspi (buildd@bos03-arm64-035) (aarch64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #4-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 02:29:55 UTC 2024 (Ubuntu 6.8.0-1004.4-raspi 6.8.1)
[    0.000000] KASLR enabled
[    0.000000] random: crng init done
[    0.000000] Machine model: Raspberry Pi 5 Model B Rev 1.0
[    0.000000] Reserved memory: created CMA memory pool at 0x0000000002000000, size 64 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] OF: reserved mem: 0x0000000002000000..0x0000000005ffffff (65536 KiB) map reusable linux,cma
[    0.000000] OF: reserved mem: 0x0000000000000000..0x000000000007ffff (512 KiB) nomap non-reusable atf@0
[    0.000000] OF: reserved mem: 0x000000003fd167e0..0x000000003fd16816 (0 KiB) nomap non-reusable nvram@0
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x00000000ffffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   [mem 0x0000000100000000-0x00000001ffffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000000007ffff]
[    0.000000]   node   0: [mem 0x0000000000080000-0x000000003fbfffff]
[    0.000000]   node   0: [mem 0x0000000040000000-0x00000001ffffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x00000001ffffffff]
[    0.000000] On node 0, zone DMA: 1024 pages in unavailable ranges
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.2
[    0.000000] percpu: Embedded 52 pages/cpu s88232 r8192 d116568 u212992
[    0.000000] pcpu-alloc: s88232 r8192 d116568 u212992 alloc=52*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Detected PIPT I-cache on CPU0
[    0.000000] CPU features: detected: Virtualization Host Extensions
[    0.000000] CPU features: detected: Spectre-v4
[    0.000000] CPU features: detected: Spectre-BHB
[    0.000000] CPU features: kernel page table isolation forced ON by KASLR
[    0.000000] CPU features: detected: Kernel page table isolation (KPTI)
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Kernel command line: reboot=w coherent_pool=1M 8250.nr_uarts=1 pci=pcie_bus_safe snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=640 bcm2708_fb.fbheight=480 bcm2708_fb.fbdepth=16 bcm2708_fb.fbswap=1 smsc95xx.macaddr=D8:3A:DD:B0:63:F7 vc_mem.mem_base=0x3fc00000 vc_mem.mem_size=0x40000000  console=ttyAMA10,115200 multipath=off dwc_otg.lpm_enable=0 console=tty1 root=LABEL=writable rootfstype=ext4 rootwait fixrtc cfg80211.ieee80211_regdom=JP video=HDMI-A-1:720x720M@60D
[    0.000000] Unknown kernel command line parameters "fixrtc multipath=off", will be passed to user space.
[    0.000000] Dentry cache hash table entries: 1048576 (order: 11, 8388608 bytes, linear)
[    0.000000] Inode-cache hash table entries: 524288 (order: 10, 4194304 bytes, linear)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 2063360
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] software IO TLB: area num 4.
[    0.000000] software IO TLB: mapped [mem 0x00000000fbfff000-0x00000000fffff000] (64MB)
[    0.000000] Memory: 8009808K/8384512K available (15040K kernel code, 2704K rwdata, 4760K rodata, 6528K init, 853K bss, 309168K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 44819 entries in 176 pages
[    0.000000] ftrace: allocated 176 pages with 3 groups
[    0.000000] trace event string verifier disabled
[    0.000000] Dynamic Preempt: full
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=256 to nr_cpu_ids=4.
[    0.000000] 	Trampoline variant of Tasks RCU enabled.
[    0.000000] 	Rude variant of Tasks RCU enabled.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 100 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer(s) running at 54.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xc743ce346, max_idle_ns: 440795203123 ns
[    0.000000] sched_clock: 56 bits at 54MHz, resolution 18ns, wraps every 4398046511102ns
[    0.000185] Console: colour dummy device 80x25
[    0.000190] printk: legacy console [tty1] enabled
[    0.000387] Calibrating delay loop (skipped), value calculated using timer frequency.. 108.00 BogoMIPS (lpj=54000)
[    0.000398] pid_max: default: 32768 minimum: 301
[    0.000584] LSM: initializing lsm=lockdown,capability,yama,apparmor,integrity
[    0.000690] Yama: becoming mindful.
[    0.000744] AppArmor: AppArmor initialized
[    0.000858] Mount-cache hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.000885] Mountpoint-cache hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.001963] RCU Tasks: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1.
[    0.002029] RCU Tasks Rude: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1.
[    0.002066] RCU Tasks Trace: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1.
[    0.002170] rcu: Hierarchical SRCU implementation.
[    0.002175] rcu: 	Max phase no-delay instances is 400.
[    0.003050] smp: Bringing up secondary CPUs ...
[    0.003292] Detected PIPT I-cache on CPU1
[    0.003339] CPU1: Booted secondary processor 0x0000000100 [0x414fd0b1]
[    0.003612] Detected PIPT I-cache on CPU2
[    0.003651] CPU2: Booted secondary processor 0x0000000200 [0x414fd0b1]
[    0.003917] Detected PIPT I-cache on CPU3
[    0.003951] CPU3: Booted secondary processor 0x0000000300 [0x414fd0b1]
[    0.003995] smp: Brought up 1 node, 4 CPUs
[    0.004017] SMP: Total of 4 processors activated.
[    0.004021] CPU: All CPU(s) started at EL2
[    0.004026] CPU features: detected: 32-bit EL0 Support
[    0.004030] CPU features: detected: Data cache clean to the PoU not required for I/D coherence
[    0.004037] CPU features: detected: Common not Private translations
[    0.004042] CPU features: detected: CRC32 instructions
[    0.004046] CPU features: detected: Data cache clean to Point of Persistence
[    0.004052] CPU features: detected: RCpc load-acquire (LDAPR)
[    0.004057] CPU features: detected: LSE atomic instructions
[    0.004062] CPU features: detected: Privileged Access Never
[    0.004068] CPU features: detected: Speculative Store Bypassing Safe (SSBS)
[    0.004102] alternatives: applying system-wide alternatives
[    0.005492] CPU features: detected: Hardware dirty bit management on CPU0-3
[    0.006325] devtmpfs: initialized
[    0.010136] Enabled cp15_barrier support
[    0.010148] Enabled setend support
[    0.010251] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
[    0.010263] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.011022] pinctrl core: initialized pinctrl subsystem
[    0.011481] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.011979] DMA: preallocated 1024 KiB GFP_KERNEL pool for atomic allocations
[    0.012127] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.012317] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.012340] audit: initializing netlink subsys (disabled)
[    0.012402] audit: type=2000 audit(0.011:1): state=initialized audit_enabled=0 res=1
[    0.012570] thermal_sys: Registered thermal governor 'fair_share'
[    0.012574] thermal_sys: Registered thermal governor 'bang_bang'
[    0.012580] thermal_sys: Registered thermal governor 'step_wise'
[    0.012585] thermal_sys: Registered thermal governor 'user_space'
[    0.012606] cpuidle: using governor ladder
[    0.012623] cpuidle: using governor menu
[    0.012720] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.012766] ASID allocator initialised with 32768 entries
[    0.013139] Serial: AMBA PL011 UART driver
[    0.014380] bcm2835-mbox 107c013880.mailbox: mailbox enabled
[    0.014831] 107d001000.serial: ttyAMA10 at MMIO 0x107d001000 (irq = 15, base_baud = 0) is a PL011 rev2
[    0.014848] printk: legacy console [ttyAMA10] enabled
[    0.799478] raspberrypi-firmware soc:firmware: Attached to firmware from 2023-10-30T16:45:10, variant start_cd
[    0.810537] raspberrypi-firmware soc:firmware: Firmware hash is 30de0ba500000000000000000000000000000000
[    0.825454] Modules: 2G module region forced by RANDOMIZE_MODULE_REGION_FULL
[    0.832537] Modules: 0 pages in range for non-PLT usage
[    0.832539] Modules: 516768 pages in range for PLT usage
[    0.838117] HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages
[    0.850268] HugeTLB: 0 KiB vmemmap can be freed for a 1.00 GiB page
[    0.856564] HugeTLB: registered 32.0 MiB page size, pre-allocated 0 pages
[    0.863381] HugeTLB: 0 KiB vmemmap can be freed for a 32.0 MiB page
[    0.869673] HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages
[    0.876489] HugeTLB: 0 KiB vmemmap can be freed for a 2.00 MiB page
[    0.882782] HugeTLB: registered 64.0 KiB page size, pre-allocated 0 pages
[    0.889598] HugeTLB: 0 KiB vmemmap can be freed for a 64.0 KiB page
[    0.896594] bcm2835-dma 1000010000.dma: DMA legacy API manager, dmachans=0x1
[    0.904746] iommu: Default domain type: Translated
[    0.909560] iommu: DMA domain TLB invalidation policy: strict mode
[    0.915941] SCSI subsystem initialized
[    0.919761] usbcore: registered new interface driver usbfs
[    0.925277] usbcore: registered new interface driver hub
[    0.930621] usbcore: registered new device driver usb
[    0.935713] pps_core: LinuxPPS API ver. 1 registered
[    0.940696] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.949873] PTP clock support registered
[    0.953819] EDAC MC: Ver: 3.0.0
[    0.957424] NetLabel: Initializing
[    0.960842] NetLabel:  domain hash size = 128
[    0.965214] NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO
[    0.970922] NetLabel:  unlabeled traffic allowed by default
[    0.976680] clocksource: Switched to clocksource arch_sys_counter
[    0.983796] VFS: Disk quotas dquot_6.6.0
[    0.987758] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.994977] AppArmor: AppArmor Filesystem Enabled
[    1.002126] NET: Registered PF_INET protocol family
[    1.007188] IP idents hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    1.017336] tcp_listen_portaddr_hash hash table entries: 4096 (order: 4, 65536 bytes, linear)
[    1.025960] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    1.033747] TCP established hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    1.041980] TCP bind hash table entries: 65536 (order: 9, 2097152 bytes, linear)
[    1.051179] TCP: Hash tables configured (established 65536 bind 65536)
[    1.057933] MPTCP token hash table entries: 8192 (order: 5, 196608 bytes, linear)
[    1.065582] UDP hash table entries: 4096 (order: 5, 131072 bytes, linear)
[    1.072500] UDP-Lite hash table entries: 4096 (order: 5, 131072 bytes, linear)
[    1.079944] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    1.085648] NET: Registered PF_XDP protocol family
[    1.090464] PCI: CLS 0 bytes, default 64
[    1.094491] Trying to unpack rootfs image as initramfs...
[    1.100037] kvm [1]: IPA Size Limit: 40 bits
[    1.104417] kvm [1]: vgic interrupt IRQ9
[    1.108416] kvm [1]: VHE mode initialized successfully
[    1.114246] Initialise system trusted keyrings
[    1.118736] Key type blacklist registered
[    1.122857] workingset: timestamp_bits=46 max_order=21 bucket_order=0
[    1.129402] zbud: loaded
[    1.132811] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    1.160444] Key type asymmetric registered
[    1.164565] Asymmetric key parser 'x509' registered
[    1.169523] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 246)
[    1.177055] io scheduler mq-deadline registered
[    1.181911] irq_brcmstb_l2: registered L2 intc (/soc/intc@7d503000, parent irq: 27)
[    1.189750] irq_brcmstb_l2: registered L2 intc (/soc/intc@7d508380, parent irq: 28)
[    1.197560] irq_brcmstb_l2: registered L2 intc (/soc/intc@7d508400, parent irq: 29)
[    1.205389] irq_brcmstb_l2: registered L2 intc (/soc/intc@7d517b00, parent irq: 30)
[    1.261808] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    1.269029] iproc-rng200 107d208000.rng: hwrng registered
[    1.274572] vc-mem: phys_addr:0x00000000 mem_base=0x3fc00000 mem_size:0x40000000(1024 MiB)
[    1.283596] bcm2712-iommu-cache 1000005b00.iommuc: bcm2712_iommu_cache_probe
[    1.293473] loop: module loaded
[    1.296886] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    1.306229] usbcore: registered new interface driver lan78xx
[    1.311987] usbcore: registered new interface driver smsc95xx
[    1.318039] mousedev: PS/2 mouse device common for all mice
[    1.323658] i2c_dev: i2c /dev entries driver
[    1.329146] bcm2835-wdt bcm2835-wdt: Poweroff handler already present!
[    1.335741] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    1.339477] Freeing initrd memory: 51176K
[    1.347320] sdhci: Secure Digital Host Controller Interface driver
[    1.353554] sdhci: Copyright(c) Pierre Ossman
[    1.358008] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.363871] ledtrig-cpu: registered to indicate activity on CPUs
[    1.369916] SMCCC: SOC_ID: ARCH_SOC_ID not implemented, skipping ....
[    1.376409] hid: raw HID events driver (C) Jiri Kosina
[    1.381966] hw perfevents: enabled with armv8_cortex_a76 PMU driver, 7 counters available
[    1.390382] NET: Registered PF_INET6 protocol family
[    1.395369] watchdog: Delayed init of the lockup detector failed: -19
[    1.401842] watchdog: Hard watchdog permanently disabled
[    1.406928] Segment Routing with IPv6
[    1.410867] In-situ OAM (IOAM) with IPv6
[    1.414833] NET: Registered PF_PACKET protocol family
[    1.419949] Key type dns_resolver registered
[    1.425700] registered taskstats version 1
[    1.429893] Loading compiled-in X.509 certificates
[    1.435434] Loaded X.509 cert 'Build time autogenerated kernel key: 23a9763780cae64c76af031dc700af860b732859'
[    1.446058] Loaded X.509 cert 'Canonical Ltd. Live Patch Signing: 14df34d1a87cf37625abec039ef2bf521249b969'
[    1.456480] Loaded X.509 cert 'Canonical Ltd. Kernel Module Signing: 88f752e560a1e0737e31163a466ad7b70a850c19'
[    1.466525] blacklist: Loading compiled-in revocation X.509 certificates
[    1.473273] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing: 61482aa2830d0ab2ad5af10b7250da9033ddcef0'
[    1.483163] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2017): 242ade75ac4a15e50d50c84b0d45ff3eae707a03'
[    1.493658] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (ESM 2018): 365188c1d374d6b07c3c8f240f8ef722433d6a8b'
[    1.504502] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2019): c0746fd6c5da3ae827864651ad66ae47fe24b3e8'
[    1.514996] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2021 v1): a8d54bbb3825cfb94fa13c9f8a594a195c107b8d'
[    1.525751] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2021 v2): 4cf046892d6fd3c9a5b03f98d845f90851dc6a8c'
[    1.536511] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2021 v3): 100437bb6de6e469b581e61cd66bce3ef4ed53af'
[    1.547267] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (Ubuntu Core 2019): c1d57b8f6b743f23ee41f4f7ee292f06eecadfb9'
[    1.562745] Key type .fscrypt registered
[    1.566698] Key type fscrypt-provisioning registered
[    1.578857] Key type encrypted registered
[    1.582892] AppArmor: AppArmor sha256 policy hashing enabled
[    1.588585] ima: No TPM chip found, activating TPM-bypass!
[    1.594098] ima: Allocated hash algorithm: sha1
[    1.598672] ima: No architecture policies found
[    1.603249] evm: Initialising EVM extended attributes:
[    1.608411] evm: security.selinux
[    1.611739] evm: security.SMACK64
[    1.615062] evm: security.SMACK64EXEC
[    1.618733] evm: security.SMACK64TRANSMUTE
[    1.622844] evm: security.SMACK64MMAP
[    1.626515] evm: security.apparmor
[    1.629925] evm: security.ima
[    1.632900] evm: security.capability
[    1.636484] evm: HMAC attrs: 0x1
[    1.641379] bcm2712-iommu 1000005100.iommu: bcm2712_iommu_init: DEBUG_INFO = 0x20804774
[    1.649682] bcm2712-iommu 1000005100.iommu: bcm2712_iommu_probe: Success
[    1.656874] bcm2712-iommu 1000005200.iommu: bcm2712_iommu_init: DEBUG_INFO = 0x20804774
[    1.665140] bcm2712-iommu 1000005200.iommu: bcm2712_iommu_probe: Success
[    1.672302] bcm2712-iommu 1000005280.iommu: bcm2712_iommu_init: DEBUG_INFO = 0x20804774
[    1.680562] bcm2712-iommu 1000005280.iommu: bcm2712_iommu_probe: Success
[    1.687760] of_cfs_init
[    1.690242] of_cfs_init: OK
[    1.693151] clk: Disabling unused clocks
[    1.712575] Freeing unused kernel memory: 6528K
[    1.738556] Checked W+X mappings: passed, no W+X pages found
[    1.744255] Run /init as init process
[    1.747929]   with arguments:
[    1.747932]     /init
[    1.747933]     fixrtc
[    1.747935]   with environment:
[    1.747937]     HOME=/
[    1.747939]     TERM=linux
[    1.747940]     multipath=off
[    1.929873] brcm-pcie 1000120000.pcie: host bridge /axi/pcie@120000 ranges:
[    1.940077] brcm-pcie 1000120000.pcie:   No bus range found for /axi/pcie@120000, using [bus 00-ff]
[    1.950348] brcm-pcie 1000120000.pcie:      MEM 0x1f00000000..0x1ffffffffb -> 0x0000000000
[    1.958691] brcm-pcie 1000120000.pcie:      MEM 0x1c00000000..0x1effffffff -> 0x0400000000
[    1.967409] brcm-pcie 1000120000.pcie:   IB MEM 0x1f00000000..0x1f003fffff -> 0x0000000000
[    1.975765] brcm-pcie 1000120000.pcie:   IB MEM 0x0000000000..0x0fffffffff -> 0x1000000000
[    1.985456] brcm-pcie 1000120000.pcie: Forcing gen 2
[    1.990656] 107d50c000.serial: ttyS0 at MMIO 0x107d50c000 (irq = 35, base_baud = 6000000) is a Broadcom BCM7271 UART
[    2.001438] brcm-pcie 1000120000.pcie: PCI host bridge to bus 0000:00
[    2.001506] serial serial0: tty port ttyS0 registered
[    2.007922] pci_bus 0000:00: root bus resource [bus 00-ff]
[    2.015192] dwc2 1000480000.usb: supply vusb_d not found, using dummy regulator
[    2.018507] pci_bus 0000:00: root bus resource [mem 0x1f00000000-0x1ffffffffb] (bus address [0x00000000-0xfffffffb])
[    2.018511] pci_bus 0000:00: root bus resource [mem 0x1c00000000-0x1effffffff pref] (bus address [0x400000000-0x6ffffffff])
[    2.018777] dwc2 1000480000.usb: supply vusb_a not found, using dummy regulator
[    2.025869] pci 0000:00:00.0: [14e4:2712] type 01 class 0x060400 PCIe Root Port
[    2.036732] rpi-rtc soc:rpi_rtc: registered as rtc0
[    2.047628] pci 0000:00:00.0: PCI bridge to [bus 00]
[    2.047633] pci 0000:00:00.0:   bridge window [mem 0x1ff8000000-0x1ff80fffff]
[    2.047664] pci 0000:00:00.0: PME# supported from D0 D3hot
[    2.060852] rpi-rtc soc:rpi_rtc: setting system clock to 2024-05-13T13:29:26 UTC (1715606966)
[    2.063044] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    2.079427] dwc2 1000480000.usb: dwc2_core_reset: HANG! Soft Reset timeout GRSTCTL_CSFTRST
[    2.109828] dwc2: probe of 1000480000.usb failed with error -16
[    2.186691] brcm-pcie 1000120000.pcie: clkreq-mode set to default
[    2.192822] brcm-pcie 1000120000.pcie: link up, 5.0 GT/s PCIe x4 (!SSC)
[    2.199490] pci 0000:01:00.0: [1de4:0001] type 00 class 0x020000 PCIe Endpoint
[    2.206761] pci 0000:01:00.0: BAR 0 [mem 0xffffc000-0xffffffff]
[    2.212729] pci 0000:01:00.0: BAR 1 [mem 0xffc00000-0xffffffff]
[    2.218691] pci 0000:01:00.0: BAR 2 [mem 0xffff0000-0xffffffff]
[    2.224728] pci 0000:01:00.0: supports D1
[    2.228757] pci 0000:01:00.0: PME# supported from D0 D1 D3hot D3cold
[    2.237694] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    2.244350] pci 0000:00:00.0: bridge window [mem 0x1f00000000-0x1f005fffff]: assigned
[    2.251687] raid6: neonx8   gen() 11586 MB/s
[    2.252213] pci 0000:01:00.0: BAR 1 [mem 0x1f00000000-0x1f003fffff]: assigned
[    2.263660] pci 0000:01:00.0: BAR 2 [mem 0x1f00400000-0x1f0040ffff]: assigned
[    2.270828] pci 0000:01:00.0: BAR 0 [mem 0x1f00410000-0x1f00413fff]: assigned
[    2.272681] raid6: neonx4   gen() 11519 MB/s
[    2.277993] pci 0000:00:00.0: PCI bridge to [bus 01]
[    2.287256] pci 0000:00:00.0:   bridge window [mem 0x1f00000000-0x1f005fffff]
[    2.294423] pci 0000:00:00.0: Max Payload Size set to  256/ 512 (was  128), Max Read Rq  512
[    2.294680] raid6: neonx2   gen()  9862 MB/s
[    2.302904] pci 0000:01:00.0: Max Payload Size set to  256/ 256 (was  128), Max Read Rq  512
[    2.315809] pcieport 0000:00:00.0: enabling device (0000 -> 0002)
[    2.321978] pcieport 0000:00:00.0: PME: Signaling with IRQ 38
[    2.323679] raid6: neonx1   gen()  7936 MB/s
[    2.327836] pcieport 0000:00:00.0: AER: enabled with IRQ 38
[    2.337753] rp1 0000:01:00.0: bar0 len 0x4000, start 0x1f00410000, end 0x1f00413fff, flags, 0x40200
[    2.346845] rp1 0000:01:00.0: bar1 len 0x400000, start 0x1f00000000, end 0x1f003fffff, flags, 0x40200
[    2.348681] raid6: int64x8  gen()  5611 MB/s
[    2.356111] rp1 0000:01:00.0: enabling device (0000 -> 0002)
[    2.366852] rp1 0000:01:00.0: chip_id 0x20001927
[    2.376685] raid6: int64x4  gen()  5884 MB/s
[    2.378425] input: pwr_button as /devices/platform/pwr_button/input/input1
[    2.393944] sdhci-brcmstb 1000fff000.mmc: Got CD GPIO
[    2.397679] raid6: int64x2  gen()  4888 MB/s
[    2.399497] mmc0: CQHCI version 5.10
[    2.407248] mmc1: CQHCI version 5.10
[    2.413621] macb 1f00100000.ethernet eth0: Cadence GEM rev 0x00070109 at 0x1f00100000 irq 106 (d8:3a:dd:b0:63:f7)
[    2.419682] raid6: int64x1  gen()  4045 MB/s
[    2.428228] raid6: using algorithm neonx8 gen() 11586 MB/s
[    2.448997] mmc0: SDHCI controller on 1000fff000.mmc [1000fff000.mmc] using ADMA 64-bit
[    2.450684] raid6: .... xor() 8396 MB/s, rmw enabled
[    2.462048] raid6: using neon recovery algorithm
[    2.593240] mmc1: SDHCI controller on 1001100000.mmc [1001100000.mmc] using ADMA 64-bit
[    2.604632] xor: measuring software checksum speed
[    2.610497]    8regs           :  9858 MB/sec
[    2.615529]    32regs          : 15779 MB/sec
[    2.620767]    arm64_neon      : 11468 MB/sec
[    2.625144] xor: using function: 32regs (15779 MB/sec)
[    2.630777] xhci-hcd xhci-hcd.0: xHCI Host Controller
[    2.635869] xhci-hcd xhci-hcd.0: new USB bus registered, assigned bus number 1
[    2.635947] async_tx: api initialized (async)
[    2.643569] xhci-hcd xhci-hcd.0: hcc params 0x0240fe6d hci version 0x110 quirks 0x0000008000000810
[    2.652664] mmc1: new ultra high speed DDR50 SDIO card at address 0001
[    2.656519] xhci-hcd xhci-hcd.0: irq 131, io mem 0x1f00200000
[    2.668895] xhci-hcd xhci-hcd.0: xHCI Host Controller
[    2.673971] xhci-hcd xhci-hcd.0: new USB bus registered, assigned bus number 2
[    2.681225] xhci-hcd xhci-hcd.0: Host supports USB 3.0 SuperSpeed
[    2.687411] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.08
[    2.695725] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.702984] usb usb1: Product: xHCI Host Controller
[    2.707890] usb usb1: Manufacturer: Linux 6.8.0-1004-raspi xhci-hcd
[    2.714186] usb usb1: SerialNumber: xhci-hcd.0
[    2.714388] hub 1-0:1.0: USB hub found
[    2.722428] hub 1-0:1.0: 2 ports detected
[    2.726666] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.08
[    2.734975] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.734978] usb usb2: Product: xHCI Host Controller
[    2.734980] usb usb2: Manufacturer: Linux 6.8.0-1004-raspi xhci-hcd
[    2.753416] usb usb2: SerialNumber: xhci-hcd.0
[    2.753573] hub 2-0:1.0: USB hub found
[    2.761646] hub 2-0:1.0: 1 port detected
[    2.765762] xhci-hcd xhci-hcd.1: xHCI Host Controller
[    2.770841] xhci-hcd xhci-hcd.1: new USB bus registered, assigned bus number 3
[    2.778538] xhci-hcd xhci-hcd.1: hcc params 0x0240fe6d hci version 0x110 quirks 0x0000008000000810
[    2.787558] xhci-hcd xhci-hcd.1: irq 136, io mem 0x1f00300000
[    2.793406] xhci-hcd xhci-hcd.1: xHCI Host Controller
[    2.798484] xhci-hcd xhci-hcd.1: new USB bus registered, assigned bus number 4
[    2.805742] xhci-hcd xhci-hcd.1: Host supports USB 3.0 SuperSpeed
[    2.811915] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.08
[    2.820234] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.827493] usb usb3: Product: xHCI Host Controller
[    2.832388] usb usb3: Manufacturer: Linux 6.8.0-1004-raspi xhci-hcd
[    2.838688] usb usb3: SerialNumber: xhci-hcd.1
[    2.843411] hub 3-0:1.0: USB hub found
[    2.847188] hub 3-0:1.0: 2 ports detected
[    2.851402] usb usb4: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.08
[    2.854458] Btrfs loaded, zoned=yes, fsverity=no
[    2.859707] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.859709] usb usb4: Product: xHCI Host Controller
[    2.859711] usb usb4: Manufacturer: Linux 6.8.0-1004-raspi xhci-hcd
[    2.882782] usb usb4: SerialNumber: xhci-hcd.1
[    2.882922] hub 4-0:1.0: USB hub found
[    2.891016] hub 4-0:1.0: 1 port detected
[    3.092809] usb 2-1: new SuperSpeed USB device number 2 using xhci-hcd
[    3.111759] usb 2-1: New USB device found, idVendor=090c, idProduct=1000, bcdDevice=11.00
[    3.119982] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.127185] usb 2-1: Product: Flash Drive FIT
[    3.131568] usb 2-1: Manufacturer: Samsung
[    3.135680] usb 2-1: SerialNumber: 0384923090013691
[    3.213095] usb-storage 2-1:1.0: USB Mass Storage device detected
[    3.219622] scsi host0: usb-storage 2-1:1.0
[    3.223957] usbcore: registered new interface driver usb-storage
[    3.231479] usbcore: registered new interface driver uas
[    4.654954] scsi 0:0:0:0: Direct-Access     Samsung  Flash Drive FIT  1100 PQ: 0 ANSI: 6
[    4.663363] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    4.663969] sd 0:0:0:0: [sda] 250626566 512-byte logical blocks: (128 GB/120 GiB)
[    4.676397] sd 0:0:0:0: [sda] Write Protect is off
[    4.681223] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[    4.681356] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    4.692289]  sda: sda1 sda2
[    4.695231] sd 0:0:0:0: [sda] Attached SCSI removable disk
[    4.827726] EXT4-fs (sda2): mounted filesystem 1305c13b-200a-49e8-8083-80cd01552617 ro with ordered data mode. Quota mode: none.
[    5.139144] systemd[1]: Inserted module 'autofs4'
[    5.177458] systemd[1]: systemd 255.4-1ubuntu8 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
[    5.210171] systemd[1]: Detected architecture arm64.
[    5.217869] systemd[1]: Hostname set to <ubuntu>.
[    5.645539] systemd[1]: Queued start job for default target graphical.target.
[    5.671622] systemd[1]: Created slice system-modprobe.slice - Slice /system/modprobe.
[    5.680373] systemd[1]: Created slice system-serial\x2dgetty.slice - Slice /system/serial-getty.
[    5.689941] systemd[1]: Created slice system-systemd\x2dfsck.slice - Slice /system/systemd-fsck.
[    5.699142] systemd[1]: Created slice user.slice - User and Session Slice.
[    5.706204] systemd[1]: Started systemd-ask-password-wall.path - Forward Password Requests to Wall Directory Watch.
[    5.717008] systemd[1]: Set up automount proc-sys-fs-binfmt_misc.automount - Arbitrary Executable File Formats File System Automount Point.
[    5.729673] systemd[1]: Expecting device dev-disk-by\x2dlabel-system\x2dboot.device - /dev/disk/by-label/system-boot...
[    5.740570] systemd[1]: Expecting device dev-ttyAMA10.device - /dev/ttyAMA10...
[    5.747956] systemd[1]: Expecting device sys-subsystem-net-devices-wlan0.device - /sys/subsystem/net/devices/wlan0...
[    5.758693] systemd[1]: Reached target integritysetup.target - Local Integrity Protected Volumes.
[    5.767682] systemd[1]: Reached target slices.target - Slice Units.
[    5.774033] systemd[1]: Reached target snapd.mounts-pre.target - Mounting snaps.
[    5.781518] systemd[1]: Reached target swap.target - Swaps.
[    5.787178] systemd[1]: Reached target veritysetup.target - Local Verity Protected Volumes.
[    5.795737] systemd[1]: Listening on dm-event.socket - Device-mapper event daemon FIFOs.
[    5.804090] systemd[1]: Listening on lvm2-lvmpolld.socket - LVM2 poll daemon socket.
[    5.811973] systemd[1]: multipathd.socket - multipathd control socket was skipped because of an unmet condition check (ConditionKernelCommandLine=!multipath=off).
[    5.826743] systemd[1]: Listening on syslog.socket - Syslog Socket.
[    5.833217] systemd[1]: Listening on systemd-fsckd.socket - fsck to fsckd communication Socket.
[    5.842078] systemd[1]: Listening on systemd-initctl.socket - initctl Compatibility Named Pipe.
[    5.851002] systemd[1]: Listening on systemd-journald-dev-log.socket - Journal Socket (/dev/log).
[    5.860157] systemd[1]: Listening on systemd-journald.socket - Journal Socket.
[    5.867658] systemd[1]: Listening on systemd-networkd.socket - Network Service Netlink Socket.
[    5.876387] systemd[1]: systemd-pcrextend.socket - TPM2 PCR Extension (Varlink) was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
[    5.891073] systemd[1]: Listening on systemd-udevd-control.socket - udev Control Socket.
[    5.899382] systemd[1]: Listening on systemd-udevd-kernel.socket - udev Kernel Socket.
[    5.916791] systemd[1]: Mounting dev-hugepages.mount - Huge Pages File System...
[    5.925520] systemd[1]: Mounting dev-mqueue.mount - POSIX Message Queue File System...
[    5.934832] systemd[1]: Mounting sys-kernel-debug.mount - Kernel Debug File System...
[    5.943926] systemd[1]: Mounting sys-kernel-tracing.mount - Kernel Trace File System...
[    5.953497] systemd[1]: Starting keyboard-setup.service - Set the console keyboard layout...
[    5.963428] systemd[1]: Starting kmod-static-nodes.service - Create List of Static Device Nodes...
[    5.973829] systemd[1]: Starting lvm2-monitor.service - Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
[    5.987817] systemd[1]: Starting modprobe@configfs.service - Load Kernel Module configfs...
[    5.999089] systemd[1]: Starting modprobe@dm_mod.service - Load Kernel Module dm_mod...
[    6.009920] systemd[1]: Starting modprobe@drm.service - Load Kernel Module drm...
[    6.019073] systemd[1]: Starting modprobe@efi_pstore.service - Load Kernel Module efi_pstore...
[    6.029972] systemd[1]: Starting modprobe@fuse.service - Load Kernel Module fuse...
[    6.038643] device-mapper: core: CONFIG_IMA_DISABLE_HTABLE is disabled. Duplicate IMA measurements will not be recorded in the IMA log.
[    6.039287] systemd[1]: Starting modprobe@loop.service - Load Kernel Module loop...
[    6.050995] device-mapper: uevent: version 1.0.3
[    6.063383] device-mapper: ioctl: 4.48.0-ioctl (2023-03-01) initialised: dm-devel@redhat.com
[    6.063383] systemd[1]: netplan-ovs-cleanup.service - OpenVSwitch configuration for cleanup was skipped because of an unmet condition check (ConditionFileIsExecutable=/usr/bin/ovs-vsctl).
[    6.090298] systemd[1]: Starting systemd-fsck-root.service - File System Check on Root Device...
[    6.090625] fuse: init (API version 7.39)
[    6.106240] systemd[1]: Starting systemd-journald.service - Journal Service...
[    6.119903] systemd[1]: Starting systemd-modules-load.service - Load Kernel Modules...
[    6.128030] systemd[1]: systemd-pcrmachine.service - TPM2 PCR Machine ID Measurement was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
[    6.143113] systemd[1]: systemd-tpm2-setup-early.service - TPM2 SRK Setup (Early) was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
[    6.147475] systemd-journald[344]: Collecting audit messages is disabled.
[    6.159030] systemd[1]: Starting systemd-udev-trigger.service - Coldplug All udev Devices...
[    6.175655] systemd[1]: Mounted dev-hugepages.mount - Huge Pages File System.
[    6.183148] systemd[1]: Mounted dev-mqueue.mount - POSIX Message Queue File System.
[    6.191099] systemd[1]: Mounted sys-kernel-debug.mount - Kernel Debug File System.
[    6.198918] systemd[1]: Started systemd-journald.service - Journal Service.
[    6.348791] EXT4-fs (sda2): re-mounted 1305c13b-200a-49e8-8083-80cd01552617 r/w. Quota mode: none.
[    6.386059] systemd-journald[344]: Received client request to flush runtime journal.
[    6.452334] loop0: detected capacity change from 0 to 68920
[    6.471065] systemd-journald[344]: /var/log/journal/50403bee319f43f6bbf3e9439b1db4c5/system.journal: Journal file uses a different sequence number ID, rotating.
[    6.471074] systemd-journald[344]: Rotating system journal.
[    7.129109] rpi-gpiomem 107d508500.gpiomem: window base 0x107d508500 size 0x00000040
[    7.130171] rpi-gpiomem 107d508500.gpiomem: initialised 1 regions as /dev/gpiomem1
[    7.131178] rpi-gpiomem 107d517c00.gpiomem: window base 0x107d517c00 size 0x00000040
[    7.131359] rpi-gpiomem 107d517c00.gpiomem: initialised 1 regions as /dev/gpiomem2
[    7.151628] mc: Linux media interface: v0.10
[    7.152028] rpi-gpiomem 107d504100.gpiomem: window base 0x107d504100 size 0x00000020
[    7.154781] rpi-gpiomem 107d504100.gpiomem: initialised 1 regions as /dev/gpiomem3
[    7.156788] rpi-gpiomem 107d510700.gpiomem: window base 0x107d510700 size 0x00000020
[    7.158218] rpi-gpiomem 107d510700.gpiomem: initialised 1 regions as /dev/gpiomem4
[    7.158407] rpi-gpiomem 1f000d0000.gpiomem: window base 0x1f000d0000 size 0x00030000
[    7.158964] rpi-gpiomem 1f000d0000.gpiomem: initialised 1 regions as /dev/gpiomem0
[    7.173035] videodev: Linux video capture interface: v2.00
[    7.202709] pispbe 1000880000.pisp_be: bcm2712_iommu_of_xlate: MMU 1000005100.iommu
[    7.202719] pispbe 1000880000.pisp_be: bcm2712_iommu_probe_device: MMU 1000005100.iommu
[    7.202728] pispbe 1000880000.pisp_be: bcm2712_iommu_device_group: MMU 1000005100.iommu
[    7.202736] pispbe 1000880000.pisp_be: Adding to iommu group 0
[    7.202742] pispbe 1000880000.pisp_be: bcm2712_iommu_attach_dev: MMU 1000005100.iommu
[    7.202859] pispbe 1000880000.pisp_be: pispbe_probe: HW version:  0x02252700
[    7.202862] pispbe 1000880000.pisp_be: pispbe_probe: BatchStatus: 0x00000000
[    7.202864] pispbe 1000880000.pisp_be: pispbe_probe: Status:      0x00000000
[    7.202866] pispbe 1000880000.pisp_be: Register nodes for group 0
[    7.203191] pispbe 1000880000.pisp_be: input device node registered as /dev/video20
[    7.203286] pispbe 1000880000.pisp_be: tdn_input device node registered as /dev/video21
[    7.203376] pispbe 1000880000.pisp_be: stitch_input device node registered as /dev/video22
[    7.203472] pispbe 1000880000.pisp_be: hog_output device node registered as /dev/video23
[    7.203576] pispbe 1000880000.pisp_be: output0 device node registered as /dev/video24
[    7.203782] pispbe 1000880000.pisp_be: output1 device node registered as /dev/video25
[    7.204335] rpivid_hevc: module is from the staging directory, the quality is unknown, you have been warned.
[    7.204341] rpivid_hevc: module verification failed: signature and/or required key missing - tainting kernel
[    7.204957] pispbe 1000880000.pisp_be: tdn_output device node registered as /dev/video26
[    7.205086] pispbe 1000880000.pisp_be: stitch_output device node registered as /dev/video27
[    7.205758] pispbe 1000880000.pisp_be: config device node registered as /dev/video28
[    7.206183] pispbe 1000880000.pisp_be: Register nodes for group 1
[    7.206349] pispbe 1000880000.pisp_be: input device node registered as /dev/video29
[    7.211105] rpivid 1000800000.codec: bcm2712_iommu_of_xlate: MMU 1000005100.iommu
[    7.211114] rpivid 1000800000.codec: bcm2712_iommu_probe_device: MMU 1000005100.iommu
[    7.211124] rpivid 1000800000.codec: bcm2712_iommu_device_group: MMU 1000005100.iommu
[    7.211132] rpivid 1000800000.codec: Adding to iommu group 0
[    7.211135] rpivid 1000800000.codec: bcm2712_iommu_attach_dev: MMU 1000005100.iommu
[    7.211142] dw_axi_dmac_platform 1f00188000.dma: DesignWare AXI DMA Controller, 8 channels
[    7.212377] pispbe 1000880000.pisp_be: tdn_input device node registered as /dev/video30
[    7.216954] pispbe 1000880000.pisp_be: stitch_input device node registered as /dev/video31
[    7.217867] dw_spi_mmio 1f00050000.spi: DMA init failed
[    7.219106] rpivid 1000800000.codec: Device registered as /dev/video19
[    7.220723] pispbe 1000880000.pisp_be: hog_output device node registered as /dev/video32
[    7.222109] bcm2708_fb soc:fb: Unable to determine number of FBs. Disabling driver.
[    7.229909] bcm2708_fb: probe of soc:fb failed with error -2
[    7.238098] pispbe 1000880000.pisp_be: output0 device node registered as /dev/video33
[    7.250622] pispbe 1000880000.pisp_be: output1 device node registered as /dev/video34
[    7.250721] pispbe 1000880000.pisp_be: tdn_output device node registered as /dev/video35
[    7.250772] pispbe 1000880000.pisp_be: stitch_output device node registered as /dev/video36
[    7.250816] pispbe 1000880000.pisp_be: config device node registered as /dev/video37
[    7.313445] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    7.314451] Loaded X.509 cert 'benh@debian.org: 577e021cb980e0e820821ba7b54b4961b8b4fadf'
[    7.314671] Loaded X.509 cert 'romain.perier@gmail.com: 3abbc6ec146e09d1b6016ab9d6cf71dd233f0328'
[    7.317497] Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    7.319050] Loaded X.509 cert 'wens: 61c038651aabdcf94bd0ac7ff06c7248db18c600'
[    7.367176] Bluetooth: Core ver 2.22
[    7.367230] NET: Registered PF_BLUETOOTH protocol family
[    7.367233] Bluetooth: HCI device and connection manager initialized
[    7.367239] Bluetooth: HCI socket layer initialized
[    7.367243] Bluetooth: L2CAP socket layer initialized
[    7.367252] Bluetooth: SCO socket layer initialized
[    7.377414] brcmfmac: F1 signature read @0x18000000=0x15264345
[    7.380934] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    7.381275] usbcore: registered new interface driver brcmfmac
[    7.399833] Bluetooth: HCI UART driver ver 2.3
[    7.399844] Bluetooth: HCI UART protocol H4 registered
[    7.399847] Bluetooth: HCI UART protocol BCSP registered
[    7.399893] Bluetooth: HCI UART protocol LL registered
[    7.399895] Bluetooth: HCI UART protocol ATH3K registered
[    7.399909] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    7.400060] Bluetooth: HCI UART protocol Intel registered
[    7.400263] hci_uart_bcm serial0-0: supply vbat not found, using dummy regulator
[    7.400360] hci_uart_bcm serial0-0: supply vddio not found, using dummy regulator
[    7.400423] Bluetooth: HCI UART protocol Broadcom registered
[    7.400443] Bluetooth: HCI UART protocol QCA registered
[    7.400446] Bluetooth: HCI UART protocol AG6XX registered
[    7.400462] Bluetooth: HCI UART protocol Marvell registered
[    7.614503] audit: type=1400 audit(1715606971.838:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name="Discord" pid=525 comm="apparmor_parser"
[    7.614623] audit: type=1400 audit(1715606971.838:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="QtWebEngineProcess" pid=527 comm="apparmor_parser"
[    7.614927] audit: type=1400 audit(1715606971.839:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="1password" pid=524 comm="apparmor_parser"
[    7.614933] audit: type=1400 audit(1715606971.839:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name=4D6F6E676F444220436F6D70617373 pid=526 comm="apparmor_parser"
[    7.618806] audit: type=1400 audit(1715606971.842:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="buildah" pid=530 comm="apparmor_parser"
[    7.618820] audit: type=1400 audit(1715606971.842:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="brave" pid=529 comm="apparmor_parser"
[    7.619062] audit: type=1400 audit(1715606971.843:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="busybox" pid=531 comm="apparmor_parser"
[    7.621401] audit: type=1400 audit(1715606971.845:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="cam" pid=532 comm="apparmor_parser"
[    7.621884] audit: type=1400 audit(1715606971.846:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="ch-checkns" pid=533 comm="apparmor_parser"
[    7.621992] audit: type=1400 audit(1715606971.846:11): apparmor="STATUS" operation="profile_load" profile="unconfined" name="chrome" pid=535 comm="apparmor_parser"
[    7.624917] brcmfmac_wcc: brcmf_wcc_attach: executing
[    7.633593] brcmfmac: brcmf_c_process_txcap_blob: no txcap_blob available (err=-2)
[    7.635030] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Apr 15 2021 03:03:20 version 7.45.234 (4ca95bb CY) FWID 01-996384e2
[    7.740090] Bluetooth: hci0: BCM: chip id 107
[    7.740335] Bluetooth: hci0: BCM: features 0x2f
[    7.741532] Bluetooth: hci0: BCM4345C0
[    7.741540] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0000
[    7.744083] Bluetooth: hci0: BCM4345C0 'brcm/BCM4345C0.raspberrypi,5-model-b.hcd' Patch
[    7.881379] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[    8.419329] Bluetooth: hci0: BCM: features 0x2f
[    8.420711] Bluetooth: hci0: BCM43455 37.4MHz Raspberry Pi 3+-0190
[    8.420715] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0382
[    8.421022] Bluetooth: hci0: BCM: Using default device address (43:45:c0:00:1f:ac)
[   10.816931] systemd-journald[344]: /var/log/journal/50403bee319f43f6bbf3e9439b1db4c5/user-1000.journal: Journal file uses a different sequence number ID, rotating.
[   11.430262] NET: Registered PF_QIPCRTR protocol family
[   11.503337] loop1: detected capacity change from 0 to 8
[  713.134438] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /axi/pcie@120000/rp1/i2s@a0000/status
[  713.145766] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/sound/compatible
[  713.155646] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/sound/simple-audio-card,format
[  713.166744] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/sound/simple-audio-card,name
[  713.177666] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/sound/status

### Additional context

I saw @pelwell fixed an audio issue https://github.com/raspberrypi/linux/pull/5725 and maybe it's related?

**Comment by pelwell** [comment]
1. The "no matching platform" warning comes from using a version of the dtoverlay support that pre-dates the Pi 5. You can build and install an update (it's quick and easy) from https://github.com/raspberrypi/utils/tree/master/dtmerge, but I don't think it will change anything except the warning - it is just a warning, unless your overlay name has to be translated to a `-pi5` version.
2. I don't think this is the same cause as #5724 (fixed by #5725) because that bug resulted in errors in the kernel log - your kernel log has none.

Is your user in group `audio` (`groups`)? Does `sudo aplay -l` show anything?

**Comment by Nate711** [comment]
Thanks for the helpful tips! Still no luck though. What .dtb should I apply the max98357a.dtbo to? 
```
pi@ubuntu:~$ sudo adduser $USER audio
info: The user `pi' is already a member of `audio'.
```
```
pi@ubuntu:~$ sudo dtoverlay max98357a
DTOVERLAY[warn]: no matching platform found
```
```
pi@ubuntu:~$ sudo aplay -l
aplay: device_list:277: no soundcards found...
```
```
pi@ubuntu:~$ sudo dtmerge /boot/firmware/bcm2712-rpi-5-b.dtb /home/pi/merged.dtb /boot/firmware/overlays/max98357a.dtbo
DTOVERLAY[warn]: no matching platform found
```
And side question, does the actual I2S max98357a chip need to be connected for the soundcard to display? 

@pelwell Any additional suggestions? Thanks

**Comment by Nate711** [comment]
@pelwell Sorry to bug you, any ideas given the above information?

**Comment by pelwell** [comment]
If you're still getting `DTOVERLAY[warn]: no matching platform found` then you haven't updated the dtmerge utilities.

**Comment by Nate711** [comment]
Thanks @pelwell , could you tell me how to properly update the dtmerge utilities?

**Comment by pelwell** [comment]
```
$ git clone https://github.com/raspberrypi/utils.git
$ cd utils/dtmerge
```
Then follow these instructions: https://github.com/raspberrypi/utils/tree/master/dtmerge#readme

**Comment by Nate711** [comment]
@pelwell Thanks I was able to update my dtmerge utilities which fixed the issue of `DTOVERLAY[warn]: no matching platform found` appearing. As you guessed, it didn't actually fix the problem of no sound cards appearing. 

To try to isolate the issue, I made a Raspberry Pi OS Desktop 64-bit image and tried the max98357a overlay. As expected, if I either apply it with sudo dtoverlay max98357a or add to the config.txt file, I can see the sound card show up when I run `aplay -l`. 

To try to bridge the difference between my ubuntu image and the working pios image, I copied over the max98357a.dtbo overlay from the pios image to the ubuntu image. However, it did _not_ fix the issue -- no sound cards appear with `aplay -l`.

**Comment by Nate711** [comment]
Upgrading to 6.8.0-1006.6 https://launchpad.net/ubuntu/+source/linux-raspi/6.8.0-1006.6 made everything work! The max98357a overlay applies without issue and I can hear audio out the speaker. 

I wasn't able to figure out which change made it work but would be happy if someone could figure it out.

**Comment by Nate711** [comment]
Actually I still get a bug where sometimes the overlay loads correctly and other times I get an error... But at least it sometimes works.
```
[   18.169159] platform soc:sound: deferred probe pending: asoc-simple-card: parse error 
```

**Comment by Nate711** [comment]
Using the hifiberry-dac overlay instead seems to work more reliably than the max98357a overlay! I haven't seen any of the previous `parser error` errors.

My config.txt
```
# dtoverlay=max98357a
dtoverlay=hifiberry-dac
```
