### ISSUE TITLE
Kernel 6.14-rc1 (16k): Have No HDMI audio

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#6656]
### Describe the bug

I have no HDMI audio with kernel 6.14-rc1 16k. I do not see any errors/failed in the logs and everything looks like it should have audio. Playing a movie with mpv the video is jerky and no audio. Vlc seems to play smooth with no sound. Youtube video seems to be smooth with no sound. My bluetooth earbuds sound works ok.

### Steps to reproduce the behaviour

Compile and install the kernel following the official RPi Guide. I have not tested the other pi devices other than the pi5 so do not know their status.

### Device (s)

Raspberry Pi 5

### System

XFCE DE

[ray@jellyfin ~]$ uname -a
Linux jellyfin 6.14.0-rc1-v8-16k #1 SMP PREEMPT Wed Feb  5 15:37:55 CST 2025 aarch64 GNU/Linux

```
[ray@jellyfin ~]$ sudo vcgencmd version
2025/01/22 00:16:51 
Copyright (c) 2012 Broadcom
version a7753063 (release) (embedded)
```

inxi:

```
Audio:
  Device-1: bcm2712-hdmi0 driver: vc4_hdmi bus-ID: N/A
  Device-2: bcm2712-hdmi1 driver: vc4_hdmi bus-ID: N/A
  API: ALSA v: k6.14.0-rc1-v8-16k status: kernel-api
  Server-1: sndiod v: N/A status: off
  Server-2: JACK v: 1.9.22 status: off
  Server-3: PipeWire v: 1.2.7 status: active
```

aplay -l:

```
[ray@jellyfin ~]$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

### Logs

dmesg:

```
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x414fd0b1]
[    0.000000] Linux version 6.14.0-rc1-v8-16k (ray@jellyfin) (aarch64-unknown-linux-gnu-gcc (GCC) 14.1.1 20240507, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT Wed Feb  5 15:37:55 CST 2025
[    0.000000] KASLR enabled
[    0.000000] random: crng init done
[    0.000000] Machine model: Raspberry Pi 5 Model B Rev 1.0
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x000000000e000000, size 512 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] OF: reserved mem: 0x000000000e000000..0x000000002dffffff (524288 KiB) map reusable linux,cma
[    0.000000] OF: reserved mem: 0x0000000000000000..0x000000000007ffff (512 KiB) nomap non-reusable atf@0
[    0.000000] OF: reserved mem: 0x000000003fd164e0..0x000000003fd16517 (0 KiB) nomap non-reusable nvram@0
[    0.000000] NUMA: Faking a node at [mem 0x0000000000000000-0x00000001ffffffff]
[    0.000000] Faking node 0 at [mem 0x0000000000000000-0x000000003fffffff] (1024MB)
[    0.000000] Faking node 1 at [mem 0x0000000040000000-0x000000007fffffff] (1024MB)
[    0.000000] Faking node 2 at [mem 0x0000000080000000-0x00000000bfffffff] (1024MB)
[    0.000000] Faking node 3 at [mem 0x00000000c0000000-0x00000000ffffffff] (1024MB)
[    0.000000] Faking node 4 at [mem 0x0000000100000000-0x000000013fffffff] (1024MB)
[    0.000000] Faking node 5 at [mem 0x0000000140000000-0x000000017fffffff] (1024MB)
[    0.000000] Faking node 6 at [mem 0x0000000180000000-0x00000001bfffffff] (1024MB)
[    0.000000] Faking node 7 at [mem 0x00000001c0000000-0x00000001ffffffff] (1024MB)
[    0.000000] NUMA: Initialized distance table, cnt=8
[    0.000000] NODE_DATA(0) allocated [mem 0x3f7fd1c0-0x3f7fffff]
[    0.000000] NODE_DATA(1) allocated [mem 0x7fffd1c0-0x7fffffff]
[    0.000000] NODE_DATA(2) allocated [mem 0xbfffd1c0-0xbfffffff]
[    0.000000] NODE_DATA(3) allocated [mem 0xffffd1c0-0xffffffff]
[    0.000000] NODE_DATA(4) allocated [mem 0x13fffd1c0-0x13fffffff]
[    0.000000] NODE_DATA(5) allocated [mem 0x17fffd1c0-0x17fffffff]
[    0.000000] NODE_DATA(6) allocated [mem 0x1bfffd1c0-0x1bfffffff]
[    0.000000] NODE_DATA(7) allocated [mem 0x1ffb911c0-0x1ffb93fff]
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x00000000ffffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   [mem 0x0000000100000000-0x00000001ffffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000000007ffff]
[    0.000000]   node   0: [mem 0x0000000000080000-0x000000003f7fffff]
[    0.000000]   node   1: [mem 0x0000000040000000-0x000000007fffffff]
[    0.000000]   node   2: [mem 0x0000000080000000-0x00000000bfffffff]
[    0.000000]   node   3: [mem 0x00000000c0000000-0x00000000ffffffff]
[    0.000000]   node   4: [mem 0x0000000100000000-0x000000013fffffff]
[    0.000000]   node   5: [mem 0x0000000140000000-0x000000017fffffff]
[    0.000000]   node   6: [mem 0x0000000180000000-0x00000001bfffffff]
[    0.000000]   node   7: [mem 0x00000001c0000000-0x00000001ffffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000003f7fffff]
[    0.000000] Initmem setup node 1 [mem 0x0000000040000000-0x000000007fffffff]
[    0.000000] Initmem setup node 2 [mem 0x0000000080000000-0x00000000bfffffff]
[    0.000000] Initmem setup node 3 [mem 0x00000000c0000000-0x00000000ffffffff]
[    0.000000] Initmem setup node 4 [mem 0x0000000100000000-0x000000013fffffff]
[    0.000000] Initmem setup node 5 [mem 0x0000000140000000-0x000000017fffffff]
[    0.000000] Initmem setup node 6 [mem 0x0000000180000000-0x00000001bfffffff]
[    0.000000] Initmem setup node 7 [mem 0x00000001c0000000-0x00000001ffffffff]
[    0.000000] On node 1, zone DMA: 512 pages in unavailable ranges
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.2
[    0.000000] percpu: Embedded 9 pages/cpu s94552 r8192 d44712 u147456
[    0.000000] pcpu-alloc: s94552 r8192 d44712 u147456 alloc=9*16384
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Detected PIPT I-cache on CPU0
[    0.000000] CPU features: detected: Virtualization Host Extensions
[    0.000000] CPU features: detected: Spectre-v4
[    0.000000] CPU features: detected: Spectre-BHB
[    0.000000] CPU features: kernel page table isolation forced ON by KASLR
[    0.000000] CPU features: detected: Kernel page table isolation (KPTI)
[    0.000000] CPU features: detected: SSBS not fully self-synchronizing
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Kernel command line: reboot=w coherent_pool=1M 8250.nr_uarts=1 pci=pcie_bus_safe cgroup_disable=memory numa_policy=interleave  numa=fake=8 system_heap.max_order=0 smsc95xx.macaddr=D8:3A:DD:BB:67:3A vc_mem.mem_base=0x3fc00000 vc_mem.mem_size=0x40000000  root=PARTUUID=cb41f4dc-03 rw rootwait console=ttyAMA10,115200 console=tty0 selinux=0 plymouth.enable=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 usbhid.mousepoll=8 audit=0 cgroup_enable=memory psi=1 delayacct lsm=landlock,lockdown,yama,integrity,apparmor,bpf
[    0.000000] cgroup: Disabling memory control group subsystem
[    0.000000] mempolicy: NUMA default policy overridden to 'interleave:0-7'
[    0.000000] audit: disabled (until reboot)
[    0.000000] cgroup: Enabling memory control group subsystem
[    0.000000] Unknown kernel command line parameters "selinux=0", will be passed to user space.
[    0.000000] printk: log buffer data + meta data: 131072 + 458752 = 589824 bytes
[    0.000000] Fallback order for Node 0: 0 1 2 3 4 5 6 7 
[    0.000000] Fallback order for Node 1: 1 2 3 4 5 6 7 0 
[    0.000000] Fallback order for Node 2: 2 3 4 5 6 7 0 1 
[    0.000000] Fallback order for Node 3: 3 4 5 6 7 0 1 2 
[    0.000000] Fallback order for Node 4: 4 5 6 7 0 1 2 3 
[    0.000000] Fallback order for Node 5: 5 6 7 0 1 2 3 4 
[    0.000000] Fallback order for Node 6: 6 7 0 1 2 3 4 5 
[    0.000000] Fallback order for Node 7: 7 0 1 2 3 4 5 6 
[    0.000000] Built 8 zonelists, mobility grouping on.  Total pages: 523776
[    0.000000] Policy zone: Normal
[    0.000000] mem auto-init: stack:all(zero), heap alloc:off, heap free:off
[    0.000000] software IO TLB: area num 4.
[    0.000000] software IO TLB: mapped [mem 0x00000000fbffc000-0x00000000ffffc000] (64MB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=8
[    0.000000] ftrace: allocating 45275 entries in 45 pages
[    0.000000] ftrace: allocated 45 pages with 4 groups
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu: 	RCU event tracing is enabled.
[    0.000000] 	Trampoline variant of Tasks RCU enabled.
[    0.000000] 	Rude variant of Tasks RCU enabled.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] RCU Tasks: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=4.
[    0.000000] RCU Tasks Rude: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=4.
[    0.000000] RCU Tasks Trace: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=4.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer(s) running at 54.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xc743ce346, max_idle_ns: 440795203123 ns
[    0.000000] sched_clock: 56 bits at 54MHz, resolution 18ns, wraps every 4398046511102ns
[    0.000080] Console: colour dummy device 80x25
[    0.000084] printk: legacy console [tty0] enabled
[    0.000265] Calibrating delay loop (skipped), value calculated using timer frequency.. 108.00 BogoMIPS (lpj=216000)
[    0.000271] pid_max: default: 32768 minimum: 301
[    0.000356] LSM: initializing lsm=capability,apparmor
[    0.000456] AppArmor: AppArmor initialized
[    0.001954] Dentry cache hash table entries: 1048576 (order: 9, 8388608 bytes, vmalloc)
[    0.002679] Inode-cache hash table entries: 524288 (order: 8, 4194304 bytes, vmalloc)
[    0.002731] Mount-cache hash table entries: 16384 (order: 3, 131072 bytes, vmalloc)
[    0.002753] Mountpoint-cache hash table entries: 16384 (order: 3, 131072 bytes, vmalloc)
[    0.016012] rcu: Hierarchical SRCU implementation.
[    0.016024] rcu: 	Max phase no-delay instances is 1000.
[    0.020023] Timer migration: 1 hierarchy levels; 8 children per group; 0 crossnode level
[    0.020317] EFI services will not be available.
[    0.024019] smp: Bringing up secondary CPUs ...
[    0.036118] Detected PIPT I-cache on CPU1
[    0.036153] CPU1: Booted secondary processor 0x0000000100 [0x414fd0b1]
[    0.040090] Detected PIPT I-cache on CPU2
[    0.040117] CPU2: Booted secondary processor 0x0000000200 [0x414fd0b1]
[    0.048124] Detected PIPT I-cache on CPU3
[    0.048141] CPU3: Booted secondary processor 0x0000000300 [0x414fd0b1]
[    0.048167] smp: Brought up 8 nodes, 4 CPUs
[    0.048181] SMP: Total of 4 processors activated.
[    0.048184] CPU: All CPU(s) started at EL2
[    0.048187] CPU features: detected: 32-bit EL0 Support
[    0.048190] CPU features: detected: Data cache clean to the PoU not required for I/D coherence
[    0.048193] CPU features: detected: Common not Private translations
[    0.048195] CPU features: detected: CRC32 instructions
[    0.048199] CPU features: detected: RCpc load-acquire (LDAPR)
[    0.048202] CPU features: detected: LSE atomic instructions
[    0.048204] CPU features: detected: Privileged Access Never
[    0.048205] CPU features: detected: RAS Extension Support
[    0.048208] CPU features: detected: Speculative Store Bypassing Safe (SSBS)
[    0.048234] alternatives: applying system-wide alternatives
[    0.049686] CPU features: detected: Hardware dirty bit management on CPU0-3
[    0.049835] Memory: 7694896K/8380416K available (14336K kernel code, 2244K rwdata, 4864K rodata, 5376K init, 633K bss, 132736K reserved, 524288K cma-reserved)
[    0.050004] devtmpfs: initialized
[    0.051658] Enabled cp15_barrier support
[    0.051665] Enabled setend support
[    0.051703] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.051710] futex hash table entries: 1024 (order: 2, 65536 bytes, vmalloc)
[    0.052845] 2G module region forced by RANDOMIZE_MODULE_REGION_FULL
[    0.052858] 0 pages in range for non-PLT usage
[    0.052860] 129332 pages in range for PLT usage
[    0.053030] pinctrl core: initialized pinctrl subsystem
[    0.053206] DMI not present or invalid.
[    0.056654] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.056989] DMA: preallocated 1024 KiB GFP_KERNEL pool for atomic allocations
[    0.057033] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.057068] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.057180] thermal_sys: Registered thermal governor 'step_wise'
[    0.057186] cpuidle: using governor menu
[    0.057248] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.057271] ASID allocator initialised with 32768 entries
[    0.057472] Serial: AMBA PL011 UART driver
[    0.058111] /soc@107c000000/interrupt-controller@7fff9000: Fixed dependency cycle(s) with /soc@107c000000/interrupt-controller@7fff9000
[    0.058229] bcm2835-mbox 107c013880.mailbox: mailbox enabled
[    0.058328] 107d001000.serial: ttyAMA10 at MMIO 0x107d001000 (irq = 16, base_baud = 0) is a PL011 rev3
[    0.058338] printk: legacy console [ttyAMA10] enabled
[    1.117628] raspberrypi-firmware soc@107c000000:firmware: Attached to firmware from 2025-01-22T00:16:51, variant start_cd
[    1.132638] raspberrypi-firmware soc@107c000000:firmware: Firmware hash is a775306300000000000000000000000000000000
[    1.155649] bcm2835-dma 1000010000.dma: DMA legacy API manager, dmachans=0x1
[    1.163151] iommu: Default domain type: Translated
[    1.167966] iommu: DMA domain TLB invalidation policy: strict mode
[    1.180287] SCSI subsystem initialized
[    1.184076] usbcore: registered new interface driver usbfs
[    1.189586] usbcore: registered new interface driver hub
[    1.194920] usbcore: registered new device driver usb
[    1.200041] pps_core: LinuxPPS API ver. 1 registered
[    1.205025] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    1.214195] PTP clock support registered
[    1.218364] vgaarb: loaded
[    1.221168] clocksource: Switched to clocksource arch_sys_counter
[    1.304030] VFS: Disk quotas dquot_6.6.0
[    1.308043] VFS: Dquot-cache hash table entries: 2048 (order 0, 16384 bytes)
[    1.315245] AppArmor: AppArmor Filesystem Enabled
[    1.321020] NET: Registered PF_INET protocol family
[    1.326090] IP idents hash table entries: 131072 (order: 6, 1048576 bytes, vmalloc)
[    1.335225] tcp_listen_portaddr_hash hash table entries: 4096 (order: 2, 65536 bytes, vmalloc)
[    1.343898] Table-perturb hash table entries: 65536 (order: 4, 262144 bytes, vmalloc)
[    1.351765] TCP established hash table entries: 65536 (order: 5, 524288 bytes, vmalloc)
[    1.359949] TCP bind hash table entries: 65536 (order: 7, 2097152 bytes, vmalloc)
[    1.368084] TCP: Hash tables configured (established 65536 bind 65536)
[    1.374752] MPTCP token hash table entries: 8192 (order: 3, 196608 bytes, vmalloc)
[    1.382402] UDP hash table entries: 4096 (order: 4, 262144 bytes, vmalloc)
[    1.389400] UDP-Lite hash table entries: 4096 (order: 4, 262144 bytes, vmalloc)
[    1.396877] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    1.402692] RPC: Registered named UNIX socket transport module.
[    1.408635] RPC: Registered udp transport module.
[    1.413353] RPC: Registered tcp transport module.
[    1.418069] RPC: Registered tcp-with-tls transport module.
[    1.423572] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    1.430041] PCI: CLS 0 bytes, default 64
[    1.434909] kvm [1]: nv: 566 coarse grained trap handlers
[    1.440436] kvm [1]: IPA Size Limit: 40 bits
[    1.444725] kvm [1]: GICV region size/alignment is unsafe, using trapping (reduced performance)
[    1.453477] kvm [1]: vgic interrupt IRQ9
[    1.457418] kvm [1]: VHE mode initialized successfully
[    1.462879] Initialise system trusted keyrings
[    1.467525] workingset: timestamp_bits=42 max_order=19 bucket_order=0
[    1.474228] NFS: Registering the id_resolver key type
[    1.479301] Key type id_resolver registered
[    1.483495] Key type id_legacy registered
[    1.487523] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    1.494248] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    1.501800] Key type asymmetric registered
[    1.505909] Asymmetric key parser 'x509' registered
[    1.510818] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 247)
[    1.518273] io scheduler mq-deadline registered
[    1.522817] io scheduler kyber registered
[    1.526848] io scheduler bfq registered
[    1.530866] irq_brcmstb_l2: registered L2 intc (/soc@107c000000/interrupt-controller@7d510600, parent irq: 27)
[    1.540954] irq_brcmstb_l2: registered L2 intc (/soc@107c000000/interrupt-controller@7c502000, parent irq: 28)
[    1.551031] irq_brcmstb_l2: registered L2 intc (/soc@107c000000/interrupt-controller@7d508380, parent irq: 29)
[    1.561105] irq_brcmstb_l2: registered L2 intc (/soc@107c000000/interrupt-controller@7d508400, parent irq: 30)
[    1.571178] irq_brcmstb_l2: registered L2 intc (/soc@107c000000/intc@7d503000, parent irq: 31)
[    1.580627] ledtrig-cpu: registered to indicate activity on CPUs
[    1.586843] simple-framebuffer 3f800000.framebuffer: framebuffer at 0x3f800000, 0x3f4800 bytes
[    1.595496] simple-framebuffer 3f800000.framebuffer: format=r5g6b5, mode=1920x1080x16, linelength=3840
[    1.605738] Console: switching to colour frame buffer device 240x67
[    1.612854] simple-framebuffer 3f800000.framebuffer: fb0: simplefb registered!
[    1.650158] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    1.656698] 107d50c000.serial: ttyS0 at MMIO 0x107d50c000 (irq = 33, base_baud = 6000000) is a Broadcom BCM7271 UART
[    1.667309] serial serial0: tty port ttyS0 registered
[    1.672582] iproc-rng200 107d208000.rng: hwrng registered
[    1.678031] vc-mem: phys_addr:0x00000000 mem_base=0x3fc00000 mem_size:0x40000000(1024 MiB)
[    1.686465] bcm2712-iommu-cache 1000005b00.iommuc: bcm2712_iommu_cache_probe
[    1.694717] brd: module loaded
[    1.698611] loop: module loaded
[    1.701849] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    1.709187] Loading iSCSI transport class v2.0-870.
[    1.714674] usbcore: registered new device driver r8152-cfgselector
[    1.720976] usbcore: registered new interface driver r8152
[    1.726491] usbcore: registered new interface driver lan78xx
[    1.732175] usbcore: registered new interface driver smsc95xx
[    1.737980] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.743761] dwc_otg: FIQ enabled
[    1.743762] dwc_otg: NAK holdoff enabled
[    1.743762] dwc_otg: FIQ split-transaction FSM enabled
[    1.743764] Module dwc_common_port init
[    1.743857] usbcore: registered new interface driver uas
[    1.749196] usbcore: registered new interface driver usb-storage
[    1.755282] mousedev: PS/2 mouse device common for all mice
[    1.768491] rpi-rtc soc@107c000000:rpi_rtc: registered as rtc0
[    1.775759] rpi-rtc soc@107c000000:rpi_rtc: setting system clock to 2025-02-05T21:53:38 UTC (1738792418)
[    1.785535] bcm2835-wdt bcm2835-wdt: Poweroff handler already present!
[    1.792093] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    1.800521] sdhci: Secure Digital Host Controller Interface driver
[    1.806747] sdhci: Copyright(c) Pierre Ossman
[    1.811150] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.816889] SMCCC: SOC_ID: ARCH_SOC_ID not implemented, skipping ....
[    1.823371] hid: raw HID events driver (C) Jiri Kosina
[    1.828539] usbcore: registered new interface driver usbhid
[    1.834133] usbhid: USB HID core driver
[    1.838199] hw perfevents: enabled with armv8_cortex_a76 PMU driver, 7 (0,8000003f) counters available
[    1.847739] NET: Registered PF_PACKET protocol family
[    1.852829] Key type dns_resolver registered
[    1.859998] registered taskstats version 1
[    1.864172] Loading compiled-in X.509 certificates
[    1.870266] Demotion targets for Node 0: null
[    1.874642] Demotion targets for Node 1: null
[    1.879369] Demotion targets for Node 2: null
[    1.884351] Demotion targets for Node 3: null
[    1.889062] Demotion targets for Node 4: null
[    1.893764] Demotion targets for Node 5: null
[    1.898459] Demotion targets for Node 6: null
[    1.903142] Demotion targets for Node 7: null
[    1.908003] Key type .fscrypt registered
[    1.912258] Key type fscrypt-provisioning registered
[    1.917567] AppArmor: AppArmor sha256 policy hashing enabled
[    1.924140] brcm-pcie 1000120000.pcie: host bridge /axi/pcie@120000 ranges:
[    1.931617] brcm-pcie 1000120000.pcie:      MEM 0x1f00000000..0x1ffffffffb -> 0x0000000000
[    1.940242] brcm-pcie 1000120000.pcie:      MEM 0x1c00000000..0x1effffffff -> 0x0400000000
[    1.948859] brcm-pcie 1000120000.pcie:   IB MEM 0x1f00000000..0x1f003fffff -> 0x0000000000
[    1.957469] brcm-pcie 1000120000.pcie:   IB MEM 0x0000000000..0x0fffffffff -> 0x1000000000
[    1.967731] brcm-pcie 1000120000.pcie: PCI host bridge to bus 0000:00
[    1.974509] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.980319] pci_bus 0000:00: root bus resource [mem 0x1f00000000-0x1ffffffffb] (bus address [0x00000000-0xfffffffb])
[    1.991193] pci_bus 0000:00: root bus resource [mem 0x1c00000000-0x1effffffff pref] (bus address [0x400000000-0x6ffffffff])
[    2.002687] pci 0000:00:00.0: [14e4:2712] type 01 class 0x060400 PCIe Root Port
[    2.010346] pci 0000:00:00.0: PCI bridge to [bus 00]
[    2.015639] pci 0000:00:00.0:   bridge window [mem 0x1f00000000-0x1f000fffff]
[    2.023110] pci 0000:00:00.0:   bridge window [mem 0x1f00000000-0x1f000fffff 64bit pref]
[    2.031552] pci 0000:00:00.0: PME# supported from D0 D3hot
[    2.037805] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    2.046163] brcm-pcie 1000120000.pcie: Forcing gen 2
[    2.153171] brcm-pcie 1000120000.pcie: clkreq-mode set to default
[    2.159594] brcm-pcie 1000120000.pcie: link up, 5.0 GT/s PCIe x4 (!SSC)
[    2.166552] pci 0000:01:00.0: [1de4:0001] type 00 class 0x020000 PCIe Endpoint
[    2.174132] pci 0000:01:00.0: BAR 0 [mem 0xffffc000-0xffffffff]
[    2.180368] pci 0000:01:00.0: BAR 1 [mem 0xffc00000-0xffffffff]
[    2.186597] pci 0000:01:00.0: BAR 2 [mem 0xffff0000-0xffffffff]
[    2.192867] pci 0000:01:00.0: supports D1
[    2.197166] pci 0000:01:00.0: PME# supported from D0 D1 D3hot D3cold
[    2.209181] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    2.216113] pci 0000:00:00.0: bridge window [mem 0x1f00000000-0x1f005fffff]: assigned
[    2.224262] pci 0000:01:00.0: BAR 1 [mem 0x1f00000000-0x1f003fffff]: assigned
[    2.231713] pci 0000:01:00.0: BAR 2 [mem 0x1f00400000-0x1f0040ffff]: assigned
[    2.239166] pci 0000:01:00.0: BAR 0 [mem 0x1f00410000-0x1f00413fff]: assigned
[    2.246620] pci 0000:00:00.0: PCI bridge to [bus 01]
[    2.251894] pci 0000:00:00.0:   bridge window [mem 0x1f00000000-0x1f005fffff]
[    2.259348] pci_bus 0000:00: resource 4 [mem 0x1f00000000-0x1ffffffffb]
[    2.266279] pci_bus 0000:00: resource 5 [mem 0x1c00000000-0x1effffffff pref]
[    2.273647] pci_bus 0000:01: resource 1 [mem 0x1f00000000-0x1f005fffff]
[    2.280579] pci 0000:00:00.0: Max Payload Size set to  256/ 512 (was  128), Max Read Rq  512
[    2.289356] pci 0000:01:00.0: Max Payload Size set to  256/ 256 (was  128), Max Read Rq  512
[    2.298178] pcieport 0000:00:00.0: enabling device (0000 -> 0002)
[    2.304615] pcieport 0000:00:00.0: PME: Signaling with IRQ 38
[    2.310729] pcieport 0000:00:00.0: AER: enabled with IRQ 38
[    2.316681] rp1 0000:01:00.0: bar0 len 0x4000, start 0x1f00410000, end 0x1f00413fff, flags, 0x40200
[    2.326069] rp1 0000:01:00.0: bar1 len 0x400000, start 0x1f00000000, end 0x1f003fffff, flags, 0x40200
[    2.335643] rp1 0000:01:00.0: enabling device (0000 -> 0002)
[    2.342174] rp1 0000:01:00.0: chip_id 0x20001927
[    2.350963] genirq: irq_chip rp1_irq_chip did not update eff. affinity mask of irq 100
[    2.371036] macb 1f00100000.ethernet eth0: Cadence GEM rev 0x00070109 at 0x1f00100000 irq 106 (d8:3a:dd:bb:67:3a)
[    2.382376] dw_axi_dmac_platform 1f00188000.dma: DesignWare AXI DMA Controller, 8 channels
[    2.391176] xhci-hcd xhci-hcd.0: xHCI Host Controller
[    2.396557] xhci-hcd xhci-hcd.0: new USB bus registered, assigned bus number 1
[    2.404550] xhci-hcd xhci-hcd.0: hcc params 0x0240fe6d hci version 0x110 quirks 0x0000808000000810
[    2.413862] xhci-hcd xhci-hcd.0: irq 131, io mem 0x1f00200000
[    2.419999] xhci-hcd xhci-hcd.0: xHCI Host Controller
[    2.425387] xhci-hcd xhci-hcd.0: new USB bus registered, assigned bus number 2
[    2.432956] xhci-hcd xhci-hcd.0: Host supports USB 3.0 SuperSpeed
[    2.439439] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.14
[    2.448065] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.455647] usb usb1: Product: xHCI Host Controller
[    2.460869] usb usb1: Manufacturer: Linux 6.14.0-rc1-v8-16k xhci-hcd
[    2.467580] usb usb1: SerialNumber: xhci-hcd.0
[    2.472450] hub 1-0:1.0: USB hub found
[    2.476557] hub 1-0:1.0: 2 ports detected
[    2.480998] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.14
[    2.489653] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.497239] usb usb2: Product: xHCI Host Controller
[    2.502484] usb usb2: Manufacturer: Linux 6.14.0-rc1-v8-16k xhci-hcd
[    2.509220] usb usb2: SerialNumber: xhci-hcd.0
[    2.514075] hub 2-0:1.0: USB hub found
[    2.518182] hub 2-0:1.0: 1 port detected
[    2.522669] xhci-hcd xhci-hcd.1: xHCI Host Controller
[    2.528072] xhci-hcd xhci-hcd.1: new USB bus registered, assigned bus number 3
[    2.536081] xhci-hcd xhci-hcd.1: hcc params 0x0240fe6d hci version 0x110 quirks 0x0000808000000810
[    2.545420] xhci-hcd xhci-hcd.1: irq 136, io mem 0x1f00300000
[    2.551555] xhci-hcd xhci-hcd.1: xHCI Host Controller
[    2.556944] xhci-hcd xhci-hcd.1: new USB bus registered, assigned bus number 4
[    2.564519] xhci-hcd xhci-hcd.1: Host supports USB 3.0 SuperSpeed
[    2.571001] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.14
[    2.579629] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.587205] usb usb3: Product: xHCI Host Controller
[    2.592417] usb usb3: Manufacturer: Linux 6.14.0-rc1-v8-16k xhci-hcd
[    2.599112] usb usb3: SerialNumber: xhci-hcd.1
[    2.603947] hub 3-0:1.0: USB hub found
[    2.608084] hub 3-0:1.0: 2 ports detected
[    2.612514] usb usb4: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.14
[    2.621144] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.628739] usb usb4: Product: xHCI Host Controller
[    2.633967] usb usb4: Manufacturer: Linux 6.14.0-rc1-v8-16k xhci-hcd
[    2.640682] usb usb4: SerialNumber: xhci-hcd.1
[    2.645526] hub 4-0:1.0: USB hub found
[    2.649606] hub 4-0:1.0: 1 port detected
[    2.654589] bcm2712-iommu 1000005100.iommu: bcm2712_iommu_init: DEBUG_INFO = 0x20804774
[    2.663378] bcm2712-iommu 1000005100.iommu: bcm2712_iommu_probe: Success
[    2.670874] bcm2712-iommu 1000005200.iommu: bcm2712_iommu_init: DEBUG_INFO = 0x20804774
[    2.679623] bcm2712-iommu 1000005200.iommu: bcm2712_iommu_probe: Success
[    2.687089] bcm2712-iommu 1000005280.iommu: bcm2712_iommu_init: DEBUG_INFO = 0x20804774
[    2.695827] bcm2712-iommu 1000005280.iommu: bcm2712_iommu_probe: Success
[    2.702988] sdhci-brcmstb 1000fff000.mmc: Got CD GPIO
[    2.708679] mmc1: CQHCI version 5.10
[    2.713083] of_cfs_init
[    2.716119] of_cfs_init: OK
[    2.719292] clk: Disabling unused clocks
[    2.725177] usb 1-1: new low-speed USB device number 2 using xhci-hcd
[    2.739009] PM: genpd: Disabling unused power domains
[    2.745198] mmc0: SDHCI controller on 1000fff000.mmc [1000fff000.mmc] using ADMA 64-bit
[    2.857168] usb 3-2: new low-speed USB device number 2 using xhci-hcd
[    2.899517] usb 1-1: New USB device found, idVendor=1a2c, idProduct=4324, bcdDevice= 1.10
[    2.899708] mmc1: SDHCI controller on 1001100000.mmc [1001100000.mmc] using ADMA 64-bit
[    2.899835] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.901201] Waiting for root device PARTUUID=cb41f4dc-03...
[    2.908705] usb 1-1: Product: USB Keyboard
[    2.934225] usb 1-1: Manufacturer: SEM
[    2.968263] mmc1: new UHS-I speed DDR50 SDIO card at address 0001
[    2.975491] input: SEM USB Keyboard as /devices/platform/axi/1000120000.pcie/1f00200000.usb/xhci-hcd.0/usb1/1-1/1-1:1.0/0003:1A2C:4324.0001/input/input0
[    3.034084] usb 3-2: New USB device found, idVendor=093a, idProduct=2510, bcdDevice= 1.00
[    3.042601] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.050064] usb 3-2: Product: USB Optical Mouse
[    3.054960] usb 3-2: Manufacturer: PixArt
[    3.059309] hid-generic 0003:1A2C:4324.0001: input,hidraw0: USB HID v1.10 Keyboard [SEM USB Keyboard] on usb-xhci-hcd.0-1/input0
[    3.087451] input: SEM USB Keyboard Consumer Control as /devices/platform/axi/1000120000.pcie/1f00200000.usb/xhci-hcd.0/usb1/1-1/1-1:1.1/0003:1A2C:4324.0002/input/input1
[    3.103076] input: PixArt USB Optical Mouse as /devices/platform/axi/1000120000.pcie/1f00300000.usb/xhci-hcd.1/usb3/3-2/3-2:1.0/0003:093A:2510.0003/input/input3
[    3.125269] usb 4-1: new SuperSpeed USB device number 2 using xhci-hcd
[    3.149392] usb 4-1: New USB device found, idVendor=0bc2, idProduct=a003, bcdDevice= 4.19
[    3.157929] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.165428] usb 4-1: Product: USB
[    3.169087] input: SEM USB Keyboard System Control as /devices/platform/axi/1000120000.pcie/1f00200000.usb/xhci-hcd.0/usb1/1-1/1-1:1.1/0003:1A2C:4324.0002/input/input2
[    3.184455] usb 4-1: Manufacturer: Seagate 
[    3.188994] usb 4-1: SerialNumber: 2HC015KJ
[    3.193541] hid-generic 0003:093A:2510.0003: input,hidraw1: USB HID v1.11 Mouse [PixArt USB Optical Mouse] on usb-xhci-hcd.1-2/input0
[    3.206017] hid-generic 0003:1A2C:4324.0002: input,hidraw2: USB HID v1.10 Device [SEM USB Keyboard] on usb-xhci-hcd.0-1/input1
[    3.218541] usb-storage 4-1:1.0: USB Mass Storage device detected
[    3.225104] scsi host0: usb-storage 4-1:1.0
[    4.250591] scsi 0:0:0:0: Direct-Access     Seagate  USB              0419 PQ: 0 ANSI: 6
[    4.264286] sd 0:0:0:0: [sda] 1953525167 512-byte logical blocks: (1.00 TB/932 GiB)
[    4.272865] sd 0:0:0:0: [sda] Write Protect is off
[    4.278034] sd 0:0:0:0: [sda] Mode Sense: 2b 00 10 08
[    4.278563] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, supports DPO and FUA
[    4.305752]  sda: sda1 sda2 sda3
[    4.309447] sd 0:0:0:0: [sda] Attached SCSI disk
[    4.410167] EXT4-fs (sda3): mounted filesystem 35483341-de26-433e-a6f8-6cbfbab4265e r/w with ordered data mode. Quota mode: none.
[    4.422286] VFS: Mounted root (ext4 filesystem) on device 8:3.
[    4.429133] devtmpfs: mounted
[    4.435000] Freeing unused kernel memory: 5376K
[    4.440026] Run /sbin/init as init process
[    4.444529]   with arguments:
[    4.444531]     /sbin/init
[    4.444532]   with environment:
[    4.444533]     HOME=/
[    4.444534]     TERM=linux
[    4.444535]     selinux=0
[    4.661415] NET: Registered PF_INET6 protocol family
[    4.667159] Segment Routing with IPv6
[    4.671239] In-situ OAM (IOAM) with IPv6
[    4.695271] systemd[1]: systemd 257.2-2-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +IPE +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK -BTF +XKBCOMMON +UTMP -SYSVINIT +LIBARCHIVE)
[    4.730297] systemd[1]: Detected architecture arm64.
[    4.740992] systemd[1]: Hostname set to <jellyfin>.
[    4.820953] systemd[1]: bpf-restrict-fs: BPF LSM hook not enabled in the kernel, BPF LSM not supported.
[    5.401921] systemd[1]: Queued start job for default target Graphical Interface.
[    5.454850] systemd[1]: Created slice Slice /system/dirmngr.
[    5.462068] systemd[1]: Created slice Slice /system/getty.
[    5.469002] systemd[1]: Created slice Slice /system/gpg-agent.
[    5.476260] systemd[1]: Created slice Slice /system/gpg-agent-browser.
[    5.484202] systemd[1]: Created slice Slice /system/gpg-agent-extra.
[    5.491946] systemd[1]: Created slice Slice /system/gpg-agent-ssh.
[    5.499479] systemd[1]: Created slice Slice /system/keyboxd.
[    5.506477] systemd[1]: Created slice Slice /system/modprobe.
[    5.513551] systemd[1]: Created slice Slice /system/serial-getty.
[    5.520869] systemd[1]: Created slice User and Session Slice.
[    5.527637] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    5.536554] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    5.545249] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    5.555641] systemd[1]: Expecting device /dev/disk/by-partuuid/cb41f4dc-01...
[    5.563733] systemd[1]: Expecting device /dev/ttyAMA10...
[    5.570061] systemd[1]: Reached target Local Encrypted Volumes.
[    5.576914] systemd[1]: Reached target Local Integrity Protected Volumes.
[    5.584634] systemd[1]: Reached target Path Units.
[    5.590305] systemd[1]: Reached target Remote Encrypted Volumes.
[    5.597189] systemd[1]: Reached target Remote File Systems.
[    5.603619] systemd[1]: Reached target Slice Units.
[    5.609350] systemd[1]: Reached target Mounting snaps.
[    5.615324] systemd[1]: Reached target Swaps.
[    5.620485] systemd[1]: Reached target System Time Set.
[    5.626524] systemd[1]: Reached target Local Verity Protected Volumes.
[    5.633939] systemd[1]: Listening on Device-mapper event daemon FIFOs.
[    5.641390] systemd[1]: Listening on LVM2 poll daemon socket.
[    5.649091] systemd[1]: Listening on Process Core Dump Socket.
[    5.656433] systemd[1]: Listening on Credential Encryption/Decryption.
[    5.663795] systemd[1]: Listening on Journal Socket (/dev/log).
[    5.670537] systemd[1]: Listening on Journal Sockets.
[    5.676395] systemd[1]: Listening on Userspace Out-Of-Memory (OOM) Killer Socket.
[    5.684625] systemd[1]: TPM PCR Measurements was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
[    5.696421] systemd[1]: Make TPM PCR Policy was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
[    5.708179] systemd[1]: Listening on udev Control Socket.
[    5.714360] systemd[1]: Listening on udev Kernel Socket.
[    5.720461] systemd[1]: Listening on User Database Manager Socket.
[    5.727479] systemd[1]: Huge Pages File System was skipped because of an unmet condition check (ConditionPathExists=/sys/kernel/mm/hugepages).
[    5.741910] systemd[1]: Mounting POSIX Message Queue File System...
[    5.765896] systemd[1]: Mounting Kernel Debug File System...
[    5.773451] systemd[1]: Mounting Kernel Trace File System...
[    5.780607] systemd[1]: tmp.mount: Directory /tmp to mount over is not empty, mounting anyway.
[    5.790697] systemd[1]: Mounting Temporary Directory /tmp...
[    5.798631] systemd[1]: Starting Load AppArmor profiles...
[    5.806273] systemd[1]: Starting Create List of Static Device Nodes...
[    5.815656] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
[    5.828307] systemd[1]: Starting Load Kernel Module configfs...
[    5.836547] systemd[1]: Starting Load Kernel Module dm_mod...
[    5.844845] systemd[1]: Starting Load Kernel Module drm...
[    5.852958] systemd[1]: Starting Load Kernel Module efi_pstore...
[    5.861453] systemd[1]: Starting Load Kernel Module fuse...
[    5.870098] device-mapper: ioctl: 4.49.0-ioctl (2025-01-17) initialised: dm-devel@lists.linux.dev
[    5.873339] systemd[1]: Starting Load Kernel Module loop...
[    5.886515] systemd[1]: Clear Stale Hibernate Storage Info was skipped because of an unmet condition check (ConditionPathExists=/sys/firmware/efi/efivars/HibernateLocation-8cf2644b-4b0b-428f-9387-6d876050dc67).
[    5.906706] fuse: init (API version 7.42)
[    5.912157] systemd[1]: Starting Journal Service...
[    5.950724] systemd[1]: Starting Load Kernel Modules...
[    5.959748] systemd[1]: Starting Userspace Out-Of-Memory (OOM) Killer...
[    5.967743] systemd[1]: TPM PCR Machine ID Measurement was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
[    5.985460] systemd[1]: Starting Remount Root and Kernel File Systems...
[    5.992986] i2c_dev: i2c /dev entries driver
[    5.998872] systemd[1]: Early TPM SRK Setup was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
[    6.001488] systemd-journald[170]: Collecting audit messages is disabled.
[    6.015779] systemd[1]: Starting Load udev Rules from Credentials...
[    6.018970] usbcore: registered new device driver usbip-host
[    6.051474] systemd[1]: Starting Coldplug All udev Devices...
[    6.062528] systemd[1]: Started Journal Service.
[    6.167301] systemd-journald[170]: Received client request to flush runtime journal.
[    6.723905] macb 1f00100000.ethernet end0: renamed from eth0
[    6.860878] rpi-gpiomem 107d508500.gpiomem: window base 0x107d508500 size 0x00000040
[    6.870998] rpi-gpiomem 107d508500.gpiomem: initialised 1 regions as /dev/gpiomem1
[    6.880587] mc: Linux media interface: v0.10
[    6.906474] rpi-gpiomem 107d517c00.gpiomem: window base 0x107d517c00 size 0x00000040
[    6.932678] rpi-gpiomem 107d517c00.gpiomem: initialised 1 regions as /dev/gpiomem2
[    6.933328] videodev: Linux video capture interface: v2.00
[    6.961219] rp1-firmware rp1_firmware: RP1 Firmware version eb39cfd516f8c90628aa9d91f52370aade5d0a55
[    6.973343] rpi-gpiomem 107d504100.gpiomem: window base 0x107d504100 size 0x00000020
[    6.986613] rpi-gpiomem 107d504100.gpiomem: initialised 1 regions as /dev/gpiomem3
[    6.997591] v3d 1002000000.v3d: [drm] Transparent Hugepage support is recommended for optimal performance on this platform!
[    7.013314] rp1-pio 1f00178000.pio: Created instance as pio0
[    7.027162] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    7.036770] rpi-gpiomem 107d510700.gpiomem: window base 0x107d510700 size 0x00000020
[    7.045655] rpi-gpiomem 107d510700.gpiomem: initialised 1 regions as /dev/gpiomem4
[    7.060692] [drm] Initialized v3d 1.0.0 for 1002000000.v3d on minor 0
[    7.068257] pispbe 1000880000.pisp_be: bcm2712_iommu_of_xlate: MMU 1000005100.iommu
[    7.073277] Loaded X.509 cert 'benh@debian.org: 577e021cb980e0e820821ba7b54b4961b8b4fadf'
[    7.082306] pispbe 1000880000.pisp_be: bcm2712_iommu_probe_device: MMU 1000005100.iommu
[    7.083147] rpivid_hevc: module is from the staging directory, the quality is unknown, you have been warned.
[    7.093375] Loaded X.509 cert 'romain.perier@gmail.com: 3abbc6ec146e09d1b6016ab9d6cf71dd233f0328'
[    7.116932] pispbe 1000880000.pisp_be: bcm2712_iommu_device_group: MMU 1000005100.iommu
[    7.118228] Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    7.130705] pispbe 1000880000.pisp_be: Adding to iommu group 0
[    7.135741] Loaded X.509 cert 'wens: 61c038651aabdcf94bd0ac7ff06c7248db18c600'
[    7.148086] pispbe 1000880000.pisp_be: bcm2712_iommu_attach_dev: MMU 1000005100.iommu
[    7.188750] rpi-gpiomem 1f000d0000.gpiomem: window base 0x1f000d0000 size 0x00030000
[    7.214022] brcmfmac: F1 signature read @0x18000000=0x15264345
[    7.217142] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    7.217423] loop0: detected capacity change from 0 to 354856
[    7.218509] usbcore: registered new interface driver brcmfmac
[    7.222765] rpivid 1000800000.codec: bcm2712_iommu_of_xlate: MMU 1000005100.iommu
[    7.222773] rpivid 1000800000.codec: bcm2712_iommu_probe_device: MMU 1000005100.iommu
[    7.222865] rpivid 1000800000.codec: bcm2712_iommu_device_group: MMU 1000005100.iommu
[    7.222870] rpivid 1000800000.codec: Adding to iommu group 0
[    7.222872] rpivid 1000800000.codec: bcm2712_iommu_attach_dev: MMU 1000005100.iommu
[    7.258324] input: pwr_button as /devices/platform/pwr_button/input/input4
[    7.265109] brcmstb-i2c 107d508200.i2c:  @97500hz registered in interrupt mode
[    7.272313] loop1: detected capacity change from 0 to 8
[    7.278731] pispbe 1000880000.pisp_be: Runtime PM usage count underflow!
[    7.300585] rpi-gpiomem 1f000d0000.gpiomem: initialised 1 regions as /dev/gpiomem0
[    7.334043] rpivid 1000800000.codec: Device registered as /dev/video19
[    7.343763] brcmstb-i2c 107d508280.i2c:  @97500hz registered in interrupt mode
[    7.373247] loop2: detected capacity change from 0 to 354808
[    7.385051] Bluetooth: Core ver 2.22
[    7.393297] vc4_hvs 107c580000.hvs: bcm2712_iommu_of_xlate: MMU 1000005200.iommu
[    7.402469] vc4_hvs 107c580000.hvs: bcm2712_iommu_probe_device: MMU 1000005200.iommu
[    7.407405] NET: Registered PF_BLUETOOTH protocol family
[    7.417159] Bluetooth: HCI device and connection manager initialized
[    7.425088] Bluetooth: HCI socket layer initialized
[    7.425808] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    7.429274] loop3: detected capacity change from 0 to 122416
[    7.431074] Bluetooth: L2CAP socket layer initialized
[    7.450134] Bluetooth: SCO socket layer initialized
[    7.457613] vc4_hvs 107c580000.hvs: bcm2712_iommu_device_group: MMU 1000005200.iommu
[    7.462866] loop4: detected capacity change from 0 to 188472
[    7.466224] vc4_hvs 107c580000.hvs: Adding to iommu group 1
[    7.479147] vc4_hvs 107c580000.hvs: bcm2712_iommu_attach_dev: MMU 1000005200.iommu
[    7.493700] Bluetooth: HCI UART driver ver 2.3
[    7.497834] brcmfmac: brcmf_c_process_txcap_blob: no txcap_blob available (err=-2)
[    7.503040] loop5: detected capacity change from 0 to 121832
[    7.507558] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Aug 29 2023 01:47:08 version 7.45.265 (28bca26 CY) FWID 01-b677b91b
[    7.523575] vc4-drm axi:gpu: bcm2712_iommu_of_xlate: MMU 1000005200.iommu
[    7.544545] vc4-drm axi:gpu: bcm2712_iommu_probe_device: MMU 1000005200.iommu
[    7.554402] Bluetooth: HCI UART protocol H4 registered
[    7.567715] vc4-drm axi:gpu: bcm2712_iommu_device_group: MMU 1000005200.iommu
[    7.581419] vc4-drm axi:gpu: Adding to iommu group 1
[    7.588820] loop6: detected capacity change from 0 to 140976
[    7.589254] vc4-drm axi:gpu: bcm2712_iommu_attach_dev: MMU 1000005200.iommu
[    7.605429] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    7.619168] hci_uart_bcm serial0-0: supply vbat not found, using dummy regulator
[    7.623305] loop7: detected capacity change from 0 to 140992
[    7.634429] hci_uart_bcm serial0-0: supply vddio not found, using dummy regulator
[    7.643964] Bluetooth: HCI UART protocol Broadcom registered
[    7.658624] Console: switching to colour dummy device 80x25
[    7.712932] vc4-drm axi:gpu: bound 107c580000.hvs (ops vc4_hvs_ops [vc4])
[    7.731445] Registered IR keymap rc-cec
[    7.745534] loop8: detected capacity change from 0 to 125408
[    7.771846] loop9: detected capacity change from 0 to 515760
[    7.774681] loop10: detected capacity change from 0 to 132448
[    7.789630] rc rc0: vc4-hdmi-0 as /devices/platform/soc@107c000000/107c701400.hdmi/rc/rc0
[    7.806862] loop11: detected capacity change from 0 to 989864
[    7.807296] loop12: detected capacity change from 0 to 481176
[    7.823580] loop13: detected capacity change from 0 to 1010608
[    7.825893] input: vc4-hdmi-0 as /devices/platform/soc@107c000000/107c701400.hdmi/rc/rc0/input5
[    7.841029] loop14: detected capacity change from 0 to 134968
[    7.857466] loop15: detected capacity change from 0 to 125528
[    7.865143] loop16: detected capacity change from 0 to 806384
[    7.872627] loop17: detected capacity change from 0 to 812280
[    7.891289] loop18: detected capacity change from 0 to 187776
[    7.898398] input: vc4-hdmi-0 HDMI Jack as /devices/platform/soc@107c000000/107c701400.hdmi/sound/card0/input6
[    7.932926] loop19: detected capacity change from 0 to 194448
[    7.950272] loop20: detected capacity change from 0 to 193384
[    7.959306] loop22: detected capacity change from 0 to 178720
[    7.960238] loop21: detected capacity change from 0 to 138248
[    7.979360] loop23: detected capacity change from 0 to 189224
[    7.997670] Bluetooth: hci0: BCM: chip id 107
[    7.999318] loop24: detected capacity change from 0 to 160376
[    8.008161] Bluetooth: hci0: BCM: features 0x2f
[    8.014034] Bluetooth: hci0: BCM4345C0
[    8.014041] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0000
[    8.026340] Bluetooth: hci0: BCM4345C0 'brcm/BCM4345C0.raspberrypi,5-model-b.hcd' Patch
[    8.030493] vc4-drm axi:gpu: bound 107c701400.hdmi (ops vc4_hdmi_ops [vc4])
[    8.053246] Registered IR keymap rc-cec
[    8.059506] loop25: detected capacity change from 0 to 78992
[    8.065395] loop26: detected capacity change from 0 to 79232
[    8.071868] rc rc1: vc4-hdmi-1 as /devices/platform/soc@107c000000/107c706400.hdmi/rc/rc1
[    8.081034] input: vc4-hdmi-1 as /devices/platform/soc@107c000000/107c706400.hdmi/rc/rc1/input7
[    8.094189] input: vc4-hdmi-1 HDMI Jack as /devices/platform/soc@107c000000/107c706400.hdmi/sound/card1/input8
[    8.107846] vc4-drm axi:gpu: bound 107c706400.hdmi (ops vc4_hdmi_ops [vc4])
[    8.115086] vc4-drm axi:gpu: bound 107c500000.mop (ops vc4_txp_ops [vc4])
[    8.122098] vc4-drm axi:gpu: bound 107c501000.moplet (ops vc4_txp_ops [vc4])
[    8.129508] vc4-drm axi:gpu: bound 107c410000.pixelvalve (ops vc4_crtc_ops [vc4])
[    8.138620] vc4-drm axi:gpu: bound 107c411000.pixelvalve (ops vc4_crtc_ops [vc4])
[    8.199928] [drm] Initialized vc4 0.0.0 for axi:gpu on minor 1
[    8.252151] FAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    8.256198] Console: switching to colour frame buffer device 170x48
[    8.289172] vc4-drm axi:gpu: [drm] fb0: vc4drmfb frame buffer device
[    8.741767] Bluetooth: hci0: BCM: features 0x2f
[    8.747911] Bluetooth: hci0: BCM43455 37.4MHz Raspberry Pi 3+-0190
[    8.754370] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0382
[    8.760950] Bluetooth: hci0: BCM: Using default device address (43:45:c0:00:1f:ac)
[   10.245868] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   10.251447] Bluetooth: BNEP filters: protocol multicast
[   10.256906] Bluetooth: BNEP socket layer initialized
[   10.264758] Bluetooth: MGMT ver 1.23
[   10.272360] NET: Registered PF_ALG protocol family
[   10.404774] loop27: detected capacity change from 0 to 8
[   10.981850] zram: Added device: zram0
[   11.001798] zram0: detected capacity change from 0 to 24759168
[   11.027460] Adding 12379568k swap on /dev/zram0.  Priority:100 extents:1 across:12379568k SS
[   11.208816] macb 1f00100000.ethernet end0: PHY [1f00100000.ethernet-ffffffff:01] driver [Broadcom BCM54213PE] (irq=POLL)
[   11.237770] macb 1f00100000.ethernet end0: configuring for phy/rgmii-id link mode
[   11.251826] macb 1f00100000.ethernet: gem-ptp-timer ptp clock registered.
[   11.288773] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[   11.837541] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[   15.083331] NET: Registered PF_VSOCK protocol family
[   15.262222] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[   15.270532] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save disabled
[   29.502417] Bluetooth: RFCOMM TTY layer initialized
[   29.507353] Bluetooth: RFCOMM socket layer initialized
[   29.512628] Bluetooth: RFCOMM ver 1.11
```

**Comment by popcornmix** [comment]
Can you confirm the kernel you tested contained https://github.com/raspberrypi/linux/commit/5745a677e82b84d9e646e19d2642fdc431309694 ?
Can you confirm 6.13 kernel works?

**Comment by pelwell** [comment]
I can confirm that 6.13 HDMI audio works, and that it's broken in 6.14. That code has been significantly reworked in 6.14 - see 9640f1437a88d8c617ff5523f1f9dc8c3ff29121. Unfortunately, reverting that commit isn't enough to make it work again.

**Comment by Dark-Sky** [comment]
> Can you confirm the kernel you tested contained [5745a67](https://github.com/raspberrypi/linux/commit/5745a677e82b84d9e646e19d2642fdc431309694) ? Can you confirm 6.13 kernel works?

Yes that is the commit I used. Sorry for not stating.
Latest 6.13 just fine at  f33efa774d3501313aa875bd09f17c6e2d2d6836.

**Comment by Dark-Sky** [comment]
> I can confirm that 6.13 HDMI audio works, and that it's broken in 6.14. That code has been significantly reworked in 6.14 - see [9640f14](https://github.com/raspberrypi/linux/commit/9640f1437a88d8c617ff5523f1f9dc8c3ff29121). Unfortunately, reverting that commit isn't enough to make it work again.

Thanks for confirming. I'm in no hurry; do what yo have to do on your end.

**Comment by 6by9** [comment]
Give me a moment. I had looked at an issue around those helpers and infoframes. I now just need to remember what and where!

**Comment by pelwell** [comment]
I'm deep in this already. Alsa seems to be repeatedly detecting an over/underrun and restarting the stream.

**Comment by pelwell** [comment]
It's looking as though the audio DMA is unpaced, which causes ALSA to report an underrun.

Ah - spot the difference - 6.13:
```
cyclic(262144, 8192) - dreq 41fa000c, dst 107c72001c
```
vs 6.14:
```
cyclic(262144, 8192) - dreq 41fa000c, dst 7c72001c
```
It's a slave DMA address translation issue.

**Comment by pelwell** [comment]
We'd dropped one of my patches that uses DMA addresses correctly - now available (until the next rebase) as https://github.com/raspberrypi/linux/commit/e51e7375ef74eaff72ff829be9fbb10aabcce4fb.

This makes me wonder how it's working upstream.

**Comment by pelwell** [comment]
Answer - they're still doing it wrong in the DMA driver:
```
		dst = c->cfg.dst_addr;
```
vs:
```
		dst = phys_to_dma(chan->device->dev, c->cfg.dst_addr);
```

**Comment by 6by9** [comment]
That's the one that I and others have tried to upstream a couple of times.

[Robin said that dma_map_resource](https://lkml.org/lkml/2024/2/5/1161) is the correct call, but needs https://lore.kernel.org/linux-iommu/20220610080802.11147-1-Sergey.Semin@baikalelectronics.ru/ to deal with dma-ranges.
Every time that has been sent upstream it's had an unsure response, and then nothing when answered.
https://lore.kernel.org/linux-arm-kernel/20240524182702.1317935-2-dave.stevenson@raspberrypi.com/

Upstream doesn't have a DMA channel assigned to the HDMI blocks, so no audio support.

**Comment by pelwell** [comment]
I think it's more complicated/less well thought out than that.

`dma_map_resource` is rarely used. Most of the occurrences appear to be in bus-mastering devices, but there are a few (3) in DMA controllers such as the pl330. Here it is called (via a helper function) from the `.device_prep_slave_sg` and `.device_prep_dma_cyclic` methods. However, there are no `.device_unprep_*` methods, so in order to get matching calls to `dma_unmap_resource` each driver has to take care to call it before either changing the mapping (address, direction, etc.) or from the `.device_free_chan_resources` method. This mapping wasn't created in `.device_alloc_chan_resources`, and the asymmetry makes it look like a kludge.

Behind the scenes, `dma_map_resource` looks like it should call `dma_direct_map_resource` for addresses which it believes are directly addressable by the DMA controller, and thence end up (with the patch mentioned above) calling `phys_to_dma_direct`. The equivalent path in `dma_direct_unmap_resource` is a no-op. `dma_map_resource` does allow for the possibility that the slave could be behind an IOMMU, but does that ever happen?

Anyway, with the one line patch to `dma_direct_map_resource` applied and replacing the offending direct calls to `phys_to_dma` with `dma_map_resource`, it currently doesn't work.

**Comment by pelwell** [comment]
> it currently doesn't work.

Correction - it does work, once you get the parameters right. I can push these patches to at least rpi-6.13.y and rpi-6.14.y.

**Comment by Dark-Sky** [comment]
Just to get on record:

v6.14-rc2 (16k) at 2784deac5dad0d04bbbc350336317f3d924bd0d3: Still does not have HDMI audio

**Comment by pelwell** [comment]
Sorry, Ray - that's because I merged the uncorrected version. It should be fixed in 08f6bbe2d993f.

**Comment by Dark-Sky** [comment]
LOL. Thanks Phil. I will give it a go.

**Comment by Dark-Sky** [comment]
Works like a champ. Thanks a lot!!

**Comment by Seegras** [comment]
I do have the same problem, with 6.14.1 on a desktop. Has this been fixed upstream?

**Comment by popcornmix** [comment]
We still have the fix in downstream rpi-6.14.y and rpi-6.15.y, so it is not in stable upstream trees.
@6by9 may know if it's been suibmitted.

**Comment by 6by9** [comment]
No, I haven't looked at upstreaming this again. The responses dried up so rapidly on both previous occasions that it seemed like no one wanted to be involved.

Upstream's Pi5 DT files have no DMA channel assigned, therefore there is no HDMI audio.
